export type WorkshopLevel = 'Basic' | 'Intermediate' | 'Advanced';

export interface WorkshopItem {
  id: string;
  domainId: string;
  domainTitle: string;
  numberInDomain: number;
  title: string;
  level: WorkshopLevel;
  duration: string;
  description: string;
  keyTopics: string[];
  projectOutcome: string;
  prerequisites: string;
  targetAudience: string;
}

export interface WorkshopDomain {
  id: string;
  domainNumber: number;
  title: string;
  shortTitle: string;
  description: string;
  trending: boolean;
  tagline: string;
  iconName: string;
  colorScheme: {
    badge: string;
    border: string;
    gradient: string;
    accent: string;
  };
  levelsSummary: {
    basic: string;
    intermediate: string;
    advanced: string;
  };
}

export interface FoundationWorkshop {
  id: string;
  number: number;
  title: string;
  tagline: string;
  duration: string;
  description: string;
  keyTopics: string[];
  handsOnOutcome: string;
}

export interface WorkshopVideoItem {
  id: string;
  title: string;
  collegeOrEvent: string;
  aspectRatio: 'landscape' | 'portrait';
  src: string;
  poster: string;
  caption: string;
  tag: string;
}

export const WORKSHOP_DOMAINS: WorkshopDomain[] = [
  {
    id: 'ai-ml',
    domainNumber: 1,
    title: 'AI & Machine Learning',
    shortTitle: 'AI & ML',
    trending: true,
    tagline: 'From Algorithms to Generative AI & Large Language Models',
    description: 'Master practical artificial intelligence, statistical machine learning, deep neural networks, computer vision, and real-world GenAI/LLM prompt architectures.',
    iconName: 'Cpu',
    colorScheme: {
      badge: 'bg-amber-500/10 text-amber-700 border-amber-500/30',
      border: 'hover:border-amber-500/60',
      gradient: 'from-amber-500/15 via-orange-500/5 to-transparent',
      accent: 'text-amber-600',
    },
    levelsSummary: {
      basic: 'Python for AI & Scikit-Learn fundamentals',
      intermediate: 'Deep Learning with TensorFlow & NLP text mining',
      advanced: 'Computer Vision with PyTorch & Generative LLMs',
    },
  },
  {
    id: 'full-stack',
    domainNumber: 2,
    title: 'Full Stack Development',
    shortTitle: 'Full Stack',
    trending: true,
    tagline: 'Modern Web Architectures from React to Cloud Microservices',
    description: 'Build enterprise-grade, responsive full-stack applications with modern frontend frameworks, scalable REST/GraphQL APIs, authentication, and cloud deployment.',
    iconName: 'Layers',
    colorScheme: {
      badge: 'bg-blue-500/10 text-blue-700 border-blue-500/30',
      border: 'hover:border-blue-500/60',
      gradient: 'from-blue-500/15 via-indigo-500/5 to-transparent',
      accent: 'text-blue-600',
    },
    levelsSummary: {
      basic: 'Modern Web Foundations & Tailwind CSS',
      intermediate: 'React.js, State Management & Express REST APIs',
      advanced: 'Full-Stack MERN/Next.js & Cloud Microservices',
    },
  },
  {
    id: 'data-science',
    domainNumber: 3,
    title: 'Data Science & Big Data',
    shortTitle: 'Data Science',
    trending: true,
    tagline: 'Transform Raw Data into Actionable Predictive Intelligence',
    description: 'Analyze real-world datasets with Pandas and Tableau, compute scalable analytics with Apache Spark, and architect resilient automated data pipelines with Airflow & Kafka.',
    iconName: 'BarChart3',
    colorScheme: {
      badge: 'bg-emerald-500/10 text-emerald-700 border-emerald-500/30',
      border: 'hover:border-emerald-500/60',
      gradient: 'from-emerald-500/15 via-teal-500/5 to-transparent',
      accent: 'text-emerald-600',
    },
    levelsSummary: {
      basic: 'Data Analysis with Pandas & Tableau Visualizations',
      intermediate: 'Exploratory Modeling & Apache Spark / PySpark',
      advanced: 'Predictive ML Pipelines & Kafka / Airflow Engineering',
    },
  },
  {
    id: 'cloud-devops',
    domainNumber: 4,
    title: 'Cloud Computing & DevOps',
    shortTitle: 'Cloud & DevOps',
    trending: true,
    tagline: 'Automate Infrastructure, Containerization & CI/CD Pipelines',
    description: 'Provision secure cloud infrastructure on AWS & Azure, containerize applications with Docker, orchestrate with Kubernetes, and automate deployments with Terraform and GitHub Actions.',
    iconName: 'Cloud',
    colorScheme: {
      badge: 'bg-sky-500/10 text-sky-700 border-sky-500/30',
      border: 'hover:border-sky-500/60',
      gradient: 'from-sky-500/15 via-cyan-500/5 to-transparent',
      accent: 'text-sky-600',
    },
    levelsSummary: {
      basic: 'Cloud Fundamentals (AWS/Azure) & Linux Bash',
      intermediate: 'Docker Containers & CI/CD with GitHub Actions',
      advanced: 'Kubernetes Helm & Infrastructure as Code (Terraform)',
    },
  },
  {
    id: 'cyber-security',
    domainNumber: 5,
    title: 'Cyber Security & Ethical Hacking',
    shortTitle: 'Cyber Security',
    trending: true,
    tagline: 'Offensive Penetration Testing & Defensive Network Hardening',
    description: 'Master vulnerability scanning, ethical hacking methodologies, OWASP Top 10 web vulnerabilities, Snort/Wireshark traffic analysis, and digital forensics response protocols.',
    iconName: 'ShieldCheck',
    colorScheme: {
      badge: 'bg-rose-500/10 text-rose-700 border-rose-500/30',
      border: 'hover:border-rose-500/60',
      gradient: 'from-rose-500/15 via-red-500/5 to-transparent',
      accent: 'text-rose-600',
    },
    levelsSummary: {
      basic: 'Cybersecurity Fundamentals & Linux Security Tools',
      intermediate: 'Ethical Hacking Scanning & OWASP Web Pentesting',
      advanced: 'Network Firewalls/Wireshark & Digital Forensics',
    },
  },
  {
    id: 'game-dev',
    domainNumber: 6,
    title: 'Game Development',
    shortTitle: 'Game Dev',
    trending: true,
    tagline: 'Interactive 2D/3D Worlds, Unreal Blueprints & Multiplayer Tech',
    description: 'Design interactive gameplay mechanics with Unity & C#, master 3D physics and lighting, explore Unreal Engine Blueprints, and build networked multiplayer and AR/VR applications.',
    iconName: 'Gamepad2',
    colorScheme: {
      badge: 'bg-violet-500/10 text-violet-700 border-violet-500/30',
      border: 'hover:border-violet-500/60',
      gradient: 'from-violet-500/15 via-purple-500/5 to-transparent',
      accent: 'text-violet-600',
    },
    levelsSummary: {
      basic: 'Game Engine Concepts & 2D Unity C# Basics',
      intermediate: '3D Unity Physics/Lighting & Unreal Engine Blueprints',
      advanced: 'Multiplayer Networking & AR/VR Game Development',
    },
  },
  {
    id: 'mobile-dev',
    domainNumber: 7,
    title: 'Mobile App Development',
    shortTitle: 'Mobile Apps',
    trending: false,
    tagline: 'Cross-Platform Native Experiences with Flutter & React Native',
    description: 'Develop responsive, production-ready mobile apps using Flutter and React Native with native hardware integration, offline storage, and App Store / Google Play release pipelines.',
    iconName: 'Smartphone',
    colorScheme: {
      badge: 'bg-teal-500/10 text-teal-700 border-teal-500/30',
      border: 'hover:border-teal-500/60',
      gradient: 'from-teal-500/15 via-emerald-500/5 to-transparent',
      accent: 'text-teal-600',
    },
    levelsSummary: {
      basic: 'Mobile UI Design & Dart / Flutter Basics',
      intermediate: 'State Management, REST APIs & React Native',
      advanced: 'Native Hardware Sensors & App Store Deployments',
    },
  },
  {
    id: 'ui-ux',
    domainNumber: 8,
    title: 'UI / UX Design & Product Thinking',
    shortTitle: 'UI/UX Design',
    trending: false,
    tagline: 'Human-Centered Digital Product Systems in Figma',
    description: 'Turn complex user requirements into elegant design systems in Figma. Master wireframing, high-fidelity micro-interactions, usability testing, and developer design handoffs.',
    iconName: 'Palette',
    colorScheme: {
      badge: 'bg-fuchsia-500/10 text-fuchsia-700 border-fuchsia-500/30',
      border: 'hover:border-fuchsia-500/60',
      gradient: 'from-fuchsia-500/15 via-pink-500/5 to-transparent',
      accent: 'text-fuchsia-600',
    },
    levelsSummary: {
      basic: 'Design Thinking, Personas & Figma Wireframing',
      intermediate: 'Interactive Prototypes & Scalable Design Systems',
      advanced: 'Usability Testing, UX Audits & A/B Product Strategy',
    },
  },
  {
    id: 'blockchain',
    domainNumber: 9,
    title: 'Blockchain & Web3',
    shortTitle: 'Blockchain',
    trending: false,
    tagline: 'Decentralized Applications, Smart Contracts & Tokenomics',
    description: 'Demystify cryptographic ledgers, write and test Solidity smart contracts, connect frontends using Ethers.js, explore DeFi architectures, and perform gas & security audits.',
    iconName: 'Link2',
    colorScheme: {
      badge: 'bg-orange-500/10 text-orange-700 border-orange-500/30',
      border: 'hover:border-orange-500/60',
      gradient: 'from-orange-500/15 via-amber-500/5 to-transparent',
      accent: 'text-orange-600',
    },
    levelsSummary: {
      basic: 'Blockchain Principles, Cryptography & Wallets',
      intermediate: 'Solidity Smart Contracts & React DApp Integration',
      advanced: 'DeFi Standards (ERC-20/721) & Security Auditing',
    },
  },
  {
    id: 'iot-embedded',
    domainNumber: 10,
    title: 'Internet of Things (IoT) & Embedded Systems',
    shortTitle: 'IoT & Embedded',
    trending: false,
    tagline: 'Smart Connected Hardware, Sensors & Cloud Telemetry',
    description: 'Program microcontrollers with Arduino and C/C++, connect ESP32 devices via Wi-Fi/MQTT, harness Raspberry Pi edge computing, and pipe live sensor telemetry into cloud dashboards.',
    iconName: 'Radio',
    colorScheme: {
      badge: 'bg-cyan-500/10 text-cyan-700 border-cyan-500/30',
      border: 'hover:border-cyan-500/60',
      gradient: 'from-cyan-500/15 via-sky-500/5 to-transparent',
      accent: 'text-cyan-600',
    },
    levelsSummary: {
      basic: 'Embedded C/C++ on Arduino & Circuit Prototyping',
      intermediate: 'ESP32 Wi-Fi/Bluetooth & MQTT IoT Protocols',
      advanced: 'Raspberry Pi Linux GPIO & AWS/Azure IoT Dashboards',
    },
  },
  {
    id: 'software-testing',
    domainNumber: 11,
    title: 'Software Testing & Automation',
    shortTitle: 'QA & Automation',
    trending: false,
    tagline: 'Comprehensive Quality Assurance, Automation & Load Testing',
    description: 'Master manual test case design, Postman API verification, automated web testing using Selenium and Cypress/Playwright, mobile testing with Appium, and JMeter performance suites.',
    iconName: 'CheckCircle2',
    colorScheme: {
      badge: 'bg-lime-600/10 text-lime-800 border-lime-600/30',
      border: 'hover:border-lime-600/60',
      gradient: 'from-lime-500/15 via-emerald-500/5 to-transparent',
      accent: 'text-lime-700',
    },
    levelsSummary: {
      basic: 'Manual QA Fundamentals & Postman API Testing',
      intermediate: 'Selenium WebDriver & Modern Cypress / Playwright',
      advanced: 'Appium Mobile Testing & JMeter / k6 Performance',
    },
  },
];

export const ALL_WORKSHOPS: WorkshopItem[] = [
  // ==================== DOMAIN 1: AI & MACHINE LEARNING ====================
  {
    id: 'ai-1',
    domainId: 'ai-ml',
    domainTitle: 'AI & Machine Learning',
    numberInDomain: 1,
    title: 'Python for AI & Data Basics',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Kickstart your artificial intelligence journey by mastering essential Python data structures, vectorization with NumPy, and introductory data manipulation pipelines.',
    keyTopics: ['Python Syntax for Scientific Computing', 'NumPy Arrays & Linear Algebra Operations', 'Data Cleaning & Preprocessing Basics', 'Setting up AI Jupyter Lab Workspaces'],
    projectOutcome: 'Build an automated data cleaning and statistical summarizer script for messy datasets.',
    prerequisites: 'Basic familiarity with computer usage. No prior coding experience required.',
    targetAudience: 'Engineering and science students curious about stepping into AI and data careers.',
  },
  {
    id: 'ai-2',
    domainId: 'ai-ml',
    domainTitle: 'AI & Machine Learning',
    numberInDomain: 2,
    title: 'Intro to Machine Learning & Scikit-Learn',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Learn supervised and unsupervised learning fundamentals, regression algorithms, classification trees, model evaluation metrics, and feature selection using Scikit-Learn.',
    keyTopics: ['Supervised vs Unsupervised Paradigms', 'Linear & Logistic Regression', 'Decision Trees & Random Forests', 'Cross-Validation & Accuracy Metrics'],
    projectOutcome: 'Develop and evaluate an end-to-end customer churn or student performance predictor.',
    prerequisites: 'Foundational Python syntax or completion of Python for AI Basics.',
    targetAudience: 'Students and developers wanting to train their first practical machine learning models.',
  },
  {
    id: 'ai-3',
    domainId: 'ai-ml',
    domainTitle: 'AI & Machine Learning',
    numberInDomain: 3,
    title: 'Deep Learning with TensorFlow & Keras',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Dive beneath the surface of deep neural networks, loss functions, optimizers, backpropagation, and multi-layer perceptron training using TensorFlow and Keras.',
    keyTopics: ['Artificial Neural Networks (ANN) Architecture', 'Activation Functions & Backpropagation', 'Loss Functions & Gradient Descent Optimizers', 'Model Overfitting, Regularization & Dropout'],
    projectOutcome: 'Train a deep learning classifier on tabular and image benchmarks with custom evaluation curves.',
    prerequisites: 'Working knowledge of Python and core machine learning concepts.',
    targetAudience: 'Students eager to progress from classic algorithms into deep neural architectures.',
  },
  {
    id: 'ai-4',
    domainId: 'ai-ml',
    domainTitle: 'AI & Machine Learning',
    numberInDomain: 4,
    title: 'Natural Language Processing & Text Mining',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Learn how machines understand human language through tokenization, word embeddings, sentiment analysis, TF-IDF vectorizers, and sequence modeling.',
    keyTopics: ['Text Preprocessing, Stemming & Lemmatization', 'Word2Vec & Dense Vector Embeddings', 'Sentiment Classification on Live Tweets/Reviews', 'Sequence Models & Recurrent Architectures'],
    projectOutcome: 'Build an interactive customer sentiment analysis dashboard for live product feedback.',
    prerequisites: 'Python proficiency and basic understanding of machine learning classifiers.',
    targetAudience: 'Aspiring NLP engineers and data analysts building textual intelligence tools.',
  },
  {
    id: 'ai-5',
    domainId: 'ai-ml',
    domainTitle: 'AI & Machine Learning',
    numberInDomain: 5,
    title: 'Computer Vision with OpenCV & PyTorch',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Implement real-time visual perception algorithms, Convolutional Neural Networks (CNNs), object detection pipelines, and facial recognition with OpenCV and PyTorch.',
    keyTopics: ['Image Processing Filters & Edge Detection in OpenCV', 'Convolutional Neural Networks (CNN) Architecture', 'Transfer Learning with ResNet and MobileNet', 'Real-Time Object Detection & Camera Inference'],
    projectOutcome: 'Deploy a real-time face detection and gesture recognition camera feed.',
    prerequisites: 'Solid deep learning knowledge and comfort with PyTorch/TensorFlow.',
    targetAudience: 'Developers aiming to engineer autonomous, robotic, or video-processing AI solutions.',
  },
  {
    id: 'ai-6',
    domainId: 'ai-ml',
    domainTitle: 'AI & Machine Learning',
    numberInDomain: 6,
    title: 'Generative AI, LLMs & Prompt Engineering',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Master modern Generative AI, Transformer attention mechanisms, Retrieval-Augmented Generation (RAG) with vector databases, and enterprise prompt orchestration.',
    keyTopics: ['Transformer Attention & LLM Architectures', 'Prompt Engineering Patterns & System Directives', 'Retrieval-Augmented Generation (RAG) Systems', 'Vector Databases (ChromaDB / Pinecone) & LangChain'],
    projectOutcome: 'Build a production-style custom RAG chatbot trained on college or enterprise PDF documentation.',
    prerequisites: 'Proficiency in Python and API integration concepts.',
    targetAudience: 'Advanced developers and innovators ready to ship next-gen AI applications.',
  },

  // ==================== DOMAIN 2: FULL STACK DEVELOPMENT ====================
  {
    id: 'fs-1',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development',
    numberInDomain: 1,
    title: 'Modern Web Foundations (HTML5, CSS3, ES6+ JS)',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Establish rock-solid web development fundamentals with semantic HTML5, modern CSS flexbox/grid layouts, and contemporary JavaScript ES6+ language features.',
    keyTopics: ['Semantic HTML & Accessibility Standards', 'CSS3 Layouts: Flexbox & CSS Grid Mastery', 'ES6+ Features: Promises, Async/Await & Destructuring', 'DOM Manipulation & Dynamic Event Handling'],
    projectOutcome: 'Build an interactive, fully responsive personal portfolio and product showcase.',
    prerequisites: 'None. Suitable for complete beginners in web development.',
    targetAudience: 'Students beginning their journey into professional software engineering.',
  },
  {
    id: 'fs-2',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development',
    numberInDomain: 2,
    title: 'Responsive Design & Tailwind CSS',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master utility-first styling, mobile-first design philosophy, responsive breakpoints, custom theme configuration, and micro-animations with Tailwind CSS.',
    keyTopics: ['Utility-First CSS Thinking & Architecture', 'Mobile-First Layouts & Breakpoint Strategy', 'Tailwind Config, Custom Palettes & Plugins', 'Transitions, Transforms & Dark Mode Toggle'],
    projectOutcome: 'Design and build a polished SaaS landing page that looks flawless on mobile, tablet, and desktop.',
    prerequisites: 'Basic HTML and CSS understanding.',
    targetAudience: 'Frontend developers wanting to write clean, maintainable styles at 5x speed.',
  },
  {
    id: 'fs-3',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development',
    numberInDomain: 3,
    title: 'React.js & Frontend State Management',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Harness the power of React component composition, JSX, hooks (useState, useEffect, useMemo), custom hooks, and scalable frontend state management.',
    keyTopics: ['Component Lifecycle, Props & Virtual DOM', 'Hooks Deep-Dive: useEffect, useRef, useCallback', 'Global State Management Patterns (Context API / Zustand)', 'Consuming External APIs & Handling Async States'],
    projectOutcome: 'Create a dynamic e-commerce catalog with live cart filtering, persistence, and checkout preview.',
    prerequisites: 'Comfortable with JavaScript ES6+ syntax and DOM concepts.',
    targetAudience: 'Developers seeking to build modern, interactive single-page web applications.',
  },
  {
    id: 'fs-4',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development',
    numberInDomain: 4,
    title: 'Node.js, Express & REST API Development',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Construct high-throughput backend services using Node.js event loops, Express middleware, routing architecture, RESTful standards, and MongoDB database persistence.',
    keyTopics: ['Node.js Asynchronous Runtime & Event Loop', 'Express Routing & Modular Middleware Architecture', 'RESTful API Design Principles & HTTP Status Codes', 'MongoDB / Mongoose Schema Design & CRUD Operations'],
    projectOutcome: 'Engineer a robust REST API service for a real-time booking and user reservation system.',
    prerequisites: 'Solid JavaScript foundation.',
    targetAudience: 'Developers expanding their capabilities from frontend into backend engineering.',
  },
  {
    id: 'fs-5',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development',
    numberInDomain: 5,
    title: 'Full-Stack MERN / Next.js with Authentication',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Integrate the full stack into a single unified architecture. Master JWT token security, role-based access control, server-side rendering (SSR), and database transactions.',
    keyTopics: ['Next.js App Router & Server Components', 'JWT Authentication & Secure Cookie Handling', 'Role-Based Access Control (RBAC)', 'Production Error Handling & Data Validation (Zod)'],
    projectOutcome: 'Develop and deploy a multi-user collaborative workspace application with authentication.',
    prerequisites: 'Experience with React and basic Node.js / Express.',
    targetAudience: 'Developers wanting to build and ship production-ready, full-stack web applications.',
  },
  {
    id: 'fs-6',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development',
    numberInDomain: 6,
    title: 'Microservices, GraphQL & Cloud Deployment',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Scale modern systems beyond monolithic designs. Explore GraphQL schemas and queries, decoupled microservices communication, Docker containerization, and AWS cloud deployment.',
    keyTopics: ['Monolith to Microservices Architecture', 'GraphQL vs REST: Queries, Mutations & Resolvers', 'Decoupled Service Communication & API Gateways', 'Dockerizing Full-Stack Apps & Deploying to AWS / Vercel'],
    projectOutcome: 'Deploy a containerized microservices application powered by GraphQL and connected to AWS.',
    prerequisites: 'Proficiency in full-stack web development and REST APIs.',
    targetAudience: 'Senior students and software engineers aiming for enterprise architecture roles.',
  },

  // ==================== DOMAIN 3: DATA SCIENCE & BIG DATA ====================
  {
    id: 'ds-1',
    domainId: 'data-science',
    domainTitle: 'Data Science & Big Data',
    numberInDomain: 1,
    title: 'Data Analysis with Python, NumPy & Pandas',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Harness the core tools of modern data science: import, clean, aggregate, reshape, and extract quantitative insights from massive real-world tabular datasets.',
    keyTopics: ['Pandas DataFrames & Series Operations', 'Handling Missing Values & Outliers', 'Grouping, Merging & Pivoting Tables', 'Vectorized Numerical Computations with NumPy'],
    projectOutcome: 'Generate an exploratory analysis and insight report on a multi-million-row retail dataset.',
    prerequisites: 'Basic Python syntax.',
    targetAudience: 'Anyone looking to transition into data analytics, business intelligence, or data science.',
  },
  {
    id: 'ds-2',
    domainId: 'data-science',
    domainTitle: 'Data Science & Big Data',
    numberInDomain: 2,
    title: 'Data Visualization with Matplotlib, Seaborn & Tableau',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Transform complex numbers into persuasive visual narratives. Master statistical charts with Seaborn and Matplotlib, and build executive-ready dashboards in Tableau.',
    keyTopics: ['Visual Perception & Chart Selection Principles', 'Distribution & Correlation Plots with Seaborn', 'Customizing Publication-Quality Visuals in Matplotlib', 'Building Interactive Dashboards & Filters in Tableau'],
    projectOutcome: 'Publish an interactive multi-chart business intelligence dashboard for stakeholders.',
    prerequisites: 'Basic knowledge of data formats (CSV, Excel).',
    targetAudience: 'Aspiring data analysts, consultants, and decision-makers who present data insights.',
  },
  {
    id: 'ds-3',
    domainId: 'data-science',
    domainTitle: 'Data Science & Big Data',
    numberInDomain: 3,
    title: 'Exploratory Data Analysis & Statistical Modeling',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Formulate hypotheses and validate them with rigorous statistics. Learn hypothesis testing, p-values, probability distributions, ANOVA, and multivariate correlation analysis.',
    keyTopics: ['Descriptive & Inferential Statistics', 'Hypothesis Testing, Z-Tests & T-Tests', 'Correlation Matrices & Multicollinearity Checks', 'Feature Engineering & Variable Transformations'],
    projectOutcome: 'Conduct an end-to-end scientific hypothesis testing study on healthcare or financial data.',
    prerequisites: 'Proficiency with Pandas and basic statistical concepts.',
    targetAudience: 'Students and analysts seeking deeper statistical rigor in their analytics work.',
  },
  {
    id: 'ds-4',
    domainId: 'data-science',
    domainTitle: 'Data Science & Big Data',
    numberInDomain: 4,
    title: 'Big Data Fundamentals with Apache Spark & PySpark',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Process gigabytes to terabytes of information in parallel. Learn Spark architecture, Resilient Distributed Datasets (RDDs), Spark DataFrames, and distributed queries.',
    keyTopics: ['Distributed Computing Architecture & Cluster Concepts', 'PySpark DataFrame Transformations & Actions', 'Spark SQL for Scalable Distributed Queries', 'Handling Large-Scale Log Files & Sensor Streams'],
    projectOutcome: 'Execute high-speed distributed aggregations across millions of records using PySpark.',
    prerequisites: 'Comfortable with Python and SQL queries.',
    targetAudience: 'Engineers who need to scale analytics beyond single-machine memory constraints.',
  },
  {
    id: 'ds-5',
    domainId: 'data-science',
    domainTitle: 'Data Science & Big Data',
    numberInDomain: 5,
    title: 'Predictive Analytics & End-to-End ML Pipelines',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Architect production-ready machine learning pipelines with automated feature scaling, cross-validation, hyperparameter tuning, model serialisation, and REST API serving.',
    keyTopics: ['Scikit-Learn Pipeline & ColumnTransformer Architecture', 'Hyperparameter Search (Grid & Random Search)', 'Model Serialization with Joblib / ONNX', 'Building a FastAPI Inference Endpoint for Models'],
    projectOutcome: 'Deploy an automated predictive scoring service accessible via an HTTP API.',
    prerequisites: 'Strong machine learning and data engineering fundamentals.',
    targetAudience: 'Data scientists preparing to deploy models into real-world production environments.',
  },
  {
    id: 'ds-6',
    domainId: 'data-science',
    domainTitle: 'Data Science & Big Data',
    numberInDomain: 6,
    title: 'Data Engineering with Kafka, Airflow & Data Warehousing',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Construct real-time streaming and batch orchestration pipelines. Learn Apache Kafka event streams, Apache Airflow DAG scheduling, and cloud data warehouse schemas.',
    keyTopics: ['Event-Driven Streaming with Apache Kafka', 'DAG Scheduling & Monitoring with Apache Airflow', 'Data Warehousing Concepts (Star/Snowflake Schemas)', 'Building an End-to-End Automated ETL Pipeline'],
    projectOutcome: 'Construct an automated pipeline that streams live events via Kafka and transforms them into a data warehouse using Airflow.',
    prerequisites: 'Proficiency in Python, SQL, and database architectures.',
    targetAudience: 'Engineers aspiring to become enterprise Data Engineers and Data Architects.',
  },

  // ==================== DOMAIN 4: CLOUD COMPUTING & DEVOPS ====================
  {
    id: 'cloud-1',
    domainId: 'cloud-devops',
    domainTitle: 'Cloud Computing & DevOps',
    numberInDomain: 1,
    title: 'Cloud Fundamentals (AWS / Azure Core Services)',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Demystify cloud infrastructure models (IaaS, PaaS, SaaS). Understand virtual compute (EC2/VMs), object storage (S3/Blob), IAM security policies, and virtual private clouds (VPCs).',
    keyTopics: ['Cloud Computing Models & Shared Responsibility', 'AWS EC2 Instances & Azure Virtual Machines', 'Cloud Storage: S3 Buckets, Access Control & Lifecycles', 'IAM Roles, Policies & Multi-Factor Security'],
    projectOutcome: 'Configure and launch a hardened, secure web server on AWS with custom DNS and storage.',
    prerequisites: 'Basic understanding of computer networks and operating systems.',
    targetAudience: 'Students and IT beginners seeking industry cloud foundations.',
  },
  {
    id: 'cloud-2',
    domainId: 'cloud-devops',
    domainTitle: 'Cloud Computing & DevOps',
    numberInDomain: 2,
    title: 'Linux Essentials & Bash Scripting for Cloud',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master the command-line backbone of modern servers. Navigate Linux file hierarchies, manage user permissions, automate repetitive tasks with Bash, and manage background systemd services.',
    keyTopics: ['Linux File Systems, Permissions & Ownership (chmod/chown)', 'Process Management, SSH Keys & Remote Administration', 'Automating System Maintenance with Bash Scripts', 'Systemd Services, Cron Jobs & Log Inspection'],
    projectOutcome: 'Write a comprehensive Bash automation suite for server monitoring, log rotation, and automated backups.',
    prerequisites: 'Basic command-line curiosity. No prior Linux experience needed.',
    targetAudience: 'Aspiring DevOps engineers, system administrators, and cloud architects.',
  },
  {
    id: 'cloud-3',
    domainId: 'cloud-devops',
    domainTitle: 'Cloud Computing & DevOps',
    numberInDomain: 3,
    title: 'Containerization with Docker & Docker Compose',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Eliminate "works on my machine" bugs forever. Package applications and their dependencies into lightweight, immutable Docker containers, and orchestrate multi-container systems.',
    keyTopics: ['Containers vs Virtual Machines Architecture', 'Writing Optimized Dockerfiles & Layer Caching', 'Docker Networking, Volumes & Data Persistence', 'Multi-Container Orchestration with Docker Compose'],
    projectOutcome: 'Containerize a full-stack application with frontend, backend, and PostgreSQL database using Docker Compose.',
    prerequisites: 'Familiarity with basic web development and command-line navigation.',
    targetAudience: 'Developers looking to standardize local development and prepare for containerized deployments.',
  },
  {
    id: 'cloud-4',
    domainId: 'cloud-devops',
    domainTitle: 'Cloud Computing & DevOps',
    numberInDomain: 4,
    title: 'CI/CD Pipelines with GitHub Actions & Jenkins',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Automate software delivery pipelines from code push to production. Implement automated test suites, linting gates, Docker image publishing, and continuous deployment workflows.',
    keyTopics: ['CI/CD Principles & Continuous Delivery Best Practices', 'Writing GitHub Actions Workflows (YAML)', 'Automated Unit/Integration Test Execution', 'Building & Pushing Container Images to Docker Hub / AWS ECR'],
    projectOutcome: 'Build an automated pipeline that tests, builds, and deploys every Git pull request to a staging server.',
    prerequisites: 'Git/GitHub basics and Docker fundamentals.',
    targetAudience: 'Software developers and DevOps engineers looking to streamline release cycles.',
  },
  {
    id: 'cloud-5',
    domainId: 'cloud-devops',
    domainTitle: 'Cloud Computing & DevOps',
    numberInDomain: 5,
    title: 'Kubernetes Orchestration & Helm Deployments',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Deploy, scale, and manage containerized systems at enterprise scale. Understand Kubernetes Pods, Deployments, Services, Ingress Controllers, ConfigMaps, and Helm package charts.',
    keyTopics: ['Kubernetes Cluster Architecture & Control Plane', 'Deployments, ReplicaSets & Zero-Downtime Rolling Updates', 'Service Discovery, Ingress & Cluster Networking', 'Package Management & Template Parameterization with Helm'],
    projectOutcome: 'Deploy an auto-scaling, fault-tolerant microservices cluster on Kubernetes using custom Helm charts.',
    prerequisites: 'Solid experience with Docker and basic cloud compute concepts.',
    targetAudience: 'Engineers preparing for Kubernetes administration and modern cloud engineering roles.',
  },
  {
    id: 'cloud-6',
    domainId: 'cloud-devops',
    domainTitle: 'Cloud Computing & DevOps',
    numberInDomain: 6,
    title: 'Infrastructure as Code with Terraform & AWS CloudFormation',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Treat infrastructure as versioned, reproducible software code. Learn HashiCorp Configuration Language (HCL), state management, Terraform modules, and AWS CloudFormation templates.',
    keyTopics: ['IaC Philosophy, Declarative vs Imperative Paradigms', 'Terraform Providers, Resources & State Management', 'Writing Reusable Terraform Modules with Inputs/Outputs', 'Automating Multi-Tier VPC, RDS, and ECS Deployments'],
    projectOutcome: 'Spin up and tear down a complete AWS production VPC, database, and load-balanced cluster in seconds with Terraform.',
    prerequisites: 'Working knowledge of AWS services and cloud networking.',
    targetAudience: 'DevOps engineers, Site Reliability Engineers (SREs), and cloud infrastructure specialists.',
  },

  // ==================== DOMAIN 5: CYBER SECURITY & ETHICAL HACKING ====================
  {
    id: 'cyber-1',
    domainId: 'cyber-security',
    domainTitle: 'Cyber Security & Ethical Hacking',
    numberInDomain: 1,
    title: 'Cybersecurity Fundamentals & Network Basics',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Grasp the core pillars of information security: CIA triad (Confidentiality, Integrity, Availability), TCP/IP protocols, port scanning fundamentals, and security hygiene.',
    keyTopics: ['The CIA Triad & Threat Modeling Fundamentals', 'TCP/IP, UDP, DNS, and HTTP/HTTPS Deep-Dive', 'Common Attack Vectors: Phishing, Malware & Social Engineering', 'Basic Network Reconnaissance & Port Scanning Concepts'],
    projectOutcome: 'Conduct a threat assessment and security audit report for an educational network environment.',
    prerequisites: 'Basic computer literacy.',
    targetAudience: 'Students beginning their journey into cybersecurity and networking.',
  },
  {
    id: 'cyber-2',
    domainId: 'cyber-security',
    domainTitle: 'Cyber Security & Ethical Hacking',
    numberInDomain: 2,
    title: 'Linux for Hackers & Essential Security Tools',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Learn the specialized tools used by ethical hackers and penetration testers. Navigate Kali Linux, explore Nmap for network mapping, and use Netcat and Metasploit basics.',
    keyTopics: ['Kali Linux Architecture & Essential Tools Setup', 'Network Discovery & Active Scanning with Nmap', 'Banner Grabbing & Service Fingerprinting', 'Introduction to the Metasploit Framework'],
    projectOutcome: 'Map a virtualized target lab network and generate a comprehensive asset inventory and port report.',
    prerequisites: 'Basic command-line familiarity.',
    targetAudience: 'Aspiring penetration testers and security enthusiasts.',
  },
  {
    id: 'cyber-3',
    domainId: 'cyber-security',
    domainTitle: 'Cyber Security & Ethical Hacking',
    numberInDomain: 3,
    title: 'Ethical Hacking: Scanning, Enumeration & Vulnerability Assessment',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Perform systematic vulnerability assessments across networks and systems. Learn scanning methodologies, vulnerability enumeration with Nessus/OpenVAS, and exploit analysis.',
    keyTopics: ['Reconnaissance & OSINT (Open Source Intelligence)', 'Advanced Enumeration (SMB, SNMP, SSH, Web)', 'Vulnerability Scanning with Nessus & OpenVAS', 'Prioritizing CVEs and Writing Remediation Reports'],
    projectOutcome: 'Deliver an executive vulnerability assessment report complete with risk ratings and remediation steps.',
    prerequisites: 'Knowledge of networking and basic security tools.',
    targetAudience: 'Security students preparing for ethical hacking and vulnerability assessment roles.',
  },
  {
    id: 'cyber-4',
    domainId: 'cyber-security',
    domainTitle: 'Cyber Security & Ethical Hacking',
    numberInDomain: 4,
    title: 'Web Application Penetration Testing (OWASP Top 10)',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Uncover and exploit the most critical web vulnerabilities including SQL Injection, Cross-Site Scripting (XSS), Broken Authentication, CSRF, and SSRF using Burp Suite.',
    keyTopics: ['Burp Suite Proxy Configuration & Request Interception', 'SQL Injection (In-Band, Blind & Time-Based)', 'Cross-Site Scripting (Stored, Reflected, DOM-based)', 'Authentication Flaws, Session Hijacking & CSRF'],
    projectOutcome: 'Penetrate a deliberately vulnerable web application lab (DVWA/Juice Shop) and document full proof-of-concept exploits.',
    prerequisites: 'Basic web development concepts (HTML, JavaScript, HTTP) and networking.',
    targetAudience: 'Developers and security testers wanting to audit and protect web applications.',
  },
  {
    id: 'cyber-5',
    domainId: 'cyber-security',
    domainTitle: 'Cyber Security & Ethical Hacking',
    numberInDomain: 5,
    title: 'Network Security, Firewalls & Intrusion Detection (Snort/Wireshark)',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Build robust defenses against intrusions. Capture and inspect packet payloads with Wireshark, configure firewall rules, and write custom intrusion detection rules in Snort.',
    keyTopics: ['Deep Packet Inspection & Protocol Dissection in Wireshark', 'Configuring Stateful Firewalls & iptables / UFW', 'Snort Intrusion Detection System (IDS) Architecture', 'Writing Custom Snort Signatures for Novel Attack Patterns'],
    projectOutcome: 'Configure an active network defense lab with Snort IDS that flags and blocks live cyber attack simulations.',
    prerequisites: 'Strong network protocol understanding and Linux skills.',
    targetAudience: 'Defensive security specialists, SOC analysts, and network security engineers.',
  },
  {
    id: 'cyber-6',
    domainId: 'cyber-security',
    domainTitle: 'Cyber Security & Ethical Hacking',
    numberInDomain: 6,
    title: 'Digital Forensics, Incident Response & Malware Analysis Basics',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Investigate security breaches like a cyber investigator. Learn memory forensics with Volatility, disk image analysis with Autopsy, and basic static/dynamic malware triage.',
    keyTopics: ['Incident Response Life Cycle (NIST / SANS Frameworks)', 'RAM Memory Acquisition & Forensic Analysis (Volatility)', 'Disk Imaging, Artifact Recovery & Timeline Creation (Autopsy)', 'Static & Dynamic Malware Analysis in Safe Sandbox Labs'],
    projectOutcome: 'Investigate a simulated breach scenario: analyze a memory dump, reconstruct the hacker’s timeline, and extract the malicious payload.',
    prerequisites: 'Advanced cybersecurity knowledge and operating system internals.',
    targetAudience: 'Incident responders, forensics specialists, and senior security engineers.',
  },

  // ==================== DOMAIN 6: GAME DEVELOPMENT ====================
  {
    id: 'game-1',
    domainId: 'game-dev',
    domainTitle: 'Game Development',
    numberInDomain: 1,
    title: 'Intro to Game Development: Concepts, Engines & Logic',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Discover the foundations of video game creation: game loops, coordinate spaces, sprites, collision math, state machines, and game engine architecture.',
    keyTopics: ['Core Game Loop: Update, FixedUpdate & Render Cycles', 'Coordinate Systems & Vector Mathematics for Games', 'Collision Detection & Rigid Body Physics Concepts', 'Designing Player Mechanics & Win/Loss Conditions'],
    projectOutcome: 'Build a playable 2D arcade-style game prototype with scoring and restart mechanics.',
    prerequisites: 'No game development experience required. Basic logical thinking.',
    targetAudience: 'Students and enthusiasts excited to build their very first playable video games.',
  },
  {
    id: 'game-2',
    domainId: 'game-dev',
    domainTitle: 'Game Development',
    numberInDomain: 2,
    title: '2D Game Creation with Unity & C# Basics',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Build complete 2D games in Unity. Write C# scripts for player movement, jump mechanics, animation state transitions, tilemaps, and audio feedback.',
    keyTopics: ['Unity Interface, Scene Hierarchy & Prefabs', 'C# Scripting for Game Logic & Character Controllers', 'Tilemaps, Level Design & 2D Physics Colliders', 'UI Systems: Canvas, Health Bars, Scoreboards & Sound FX'],
    projectOutcome: 'Create a multi-level 2D platformer game with animated characters, collectibles, and sound.',
    prerequisites: 'Basic programming familiarity.',
    targetAudience: 'Creative programmers looking to build engaging 2D games in the industry’s most popular engine.',
  },
  {
    id: 'game-3',
    domainId: 'game-dev',
    domainTitle: 'Game Development',
    numberInDomain: 3,
    title: '3D Game Design, Lighting & Physics in Unity',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Transition from 2D into rich 3D worlds. Learn 3D character controllers, camera cinemachine rigs, materials and shaders, baked vs real-time lighting, and raycasting.',
    keyTopics: ['3D Coordinate Math, Quaternions & Rotations', '3D Rigidbody Physics, Colliders & Raycasting', 'Lighting Techniques: Directional, Point, Spot & Baked Lightmaps', 'Cinemachine Camera Tracking & 3D Audio Spatialization'],
    projectOutcome: 'Build an atmospheric 3D third-person exploration game with interactive environmental puzzles.',
    prerequisites: 'Comfortable with Unity 2D or basic 3D concepts.',
    targetAudience: 'Game developers wanting to build rich 3D gameplay environments.',
  },
  {
    id: 'game-4',
    domainId: 'game-dev',
    domainTitle: 'Game Development',
    numberInDomain: 4,
    title: 'Unreal Engine Fundamentals & Blueprint Visual Scripting',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Explore the high-fidelity power of Unreal Engine. Learn Blueprint visual scripting, material authoring, landscape sculpting, physics assets, and Nanite/Lumen concepts.',
    keyTopics: ['Unreal Engine Interface, Viewport & Actor Hierarchy', 'Visual Scripting with Blueprints (Variables, Events, Functions)', 'Landscape Creation, Foliage & Physically Based Materials', 'Lumen Dynamic Global Illumination & Particle Systems'],
    projectOutcome: 'Design a cinematic, high-fidelity 3D environment with interactive Blueprint gameplay mechanics.',
    prerequisites: 'Basic 3D knowledge or completion of Unity 3D.',
    targetAudience: 'Developers looking to learn Unreal Engine without immediately writing low-level C++.',
  },
  {
    id: 'game-5',
    domainId: 'game-dev',
    domainTitle: 'Game Development',
    numberInDomain: 5,
    title: 'Multiplayer Game Networking & Server-Client Architecture',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Bring players together online. Master server-client topology, state synchronization, client-side prediction, lag compensation, and multiplayer lobby matchmaking.',
    keyTopics: ['Server-Client vs Peer-to-Peer Networking Models', 'Remote Procedure Calls (RPCs) & Network Variables', 'State Replication, Interpolation & Lag Compensation', 'Lobby Systems, Matchmaking & Session Management (Netcode/Mirror)'],
    projectOutcome: 'Engineer a real-time multiplayer arena game with synchronized player movement and combat.',
    prerequisites: 'Proficiency in Unity C# or Unreal Engine Blueprints.',
    targetAudience: 'Game developers wanting to build competitive or cooperative online multiplayer games.',
  },
  {
    id: 'game-6',
    domainId: 'game-dev',
    domainTitle: 'Game Development',
    numberInDomain: 6,
    title: 'VR / AR Game Development Essentials',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Build spatial computing experiences for XR headsets and mobile AR. Learn XR Interaction Toolkits, hand tracking, spatial audio, and surface plane tracking (AR Foundation).',
    keyTopics: ['XR Hardware Architectures & Headset Ergonomics', 'Unity XR Interaction Toolkit (Grab, Teleport, UI Ray)', 'Spatial Audio & Immersive Spatial Perception', 'AR Foundation: Surface Plane Detection & World Anchors'],
    projectOutcome: 'Develop an interactive VR room-scale escape game and an AR interactive tabletop experience.',
    prerequisites: 'Solid 3D game development background in Unity.',
    targetAudience: 'Innovators interested in spatial computing, virtual reality, and augmented reality.',
  },

  // ==================== DOMAIN 7: MOBILE APP DEVELOPMENT ====================
  {
    id: 'mob-1',
    domainId: 'mobile-dev',
    domainTitle: 'Mobile App Development',
    numberInDomain: 1,
    title: 'Mobile UI Design Principles & Platform Guidelines',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Understand the design conventions that make mobile apps intuitive. Study Apple Human Interface Guidelines, Material Design 3, navigation patterns, and accessibility.',
    keyTopics: ['iOS vs Android UI/UX Conventions', 'Touch Targets, Thumb Zones & Mobile Typography', 'Navigation Patterns: Tabs, Drawers, App Bars & Modals', 'Responsive Screen Adaptations for Foldables & Tablets'],
    projectOutcome: 'Create a comprehensive mobile UI design prototype following Material 3 guidelines.',
    prerequisites: 'Basic design curiosity.',
    targetAudience: 'Aspiring mobile developers and designers.',
  },
  {
    id: 'mob-2',
    domainId: 'mobile-dev',
    domainTitle: 'Mobile App Development',
    numberInDomain: 2,
    title: 'Dart & Flutter Basics for Cross-Platform Apps',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Kickstart cross-platform app creation with Google Flutter and the Dart language. Learn the widget tree, StatelessWidget vs StatefulWidget, layouts, and hot reload.',
    keyTopics: ['Dart Language Fundamentals & OOP Paradigms', 'Flutter Architecture & The Everything-is-a-Widget Philosophy', 'Stateless vs Stateful Widgets & Rebuild Cycles', 'Layout Widgets: Column, Row, Stack, ListView & Container'],
    projectOutcome: 'Build an interactive multi-screen mobile recipe or personal tracker app in Flutter.',
    prerequisites: 'Basic programming concept knowledge.',
    targetAudience: 'Students and developers wanting to create iOS and Android apps with a single codebase.',
  },
  {
    id: 'mob-3',
    domainId: 'mobile-dev',
    domainTitle: 'Mobile App Development',
    numberInDomain: 3,
    title: 'Full Flutter App: State Management, Navigation & REST APIs',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Scale your Flutter apps with production patterns. Master state management (Provider/Riverpod/Bloc), declarative routing, and consuming live REST APIs with error handling.',
    keyTopics: ['Scalable State Management (Provider / Riverpod / Bloc)', 'Named Routes, Deep Linking & Navigation 2.0', 'Consuming REST APIs with HTTP / Dio Packages', 'Local Caching with SharedPreferences & Hive'],
    projectOutcome: 'Develop a live weather or news mobile application with persistent offline caching and API updates.',
    prerequisites: 'Basic Flutter knowledge.',
    targetAudience: 'Flutter developers wanting to build clean, architecturally sound apps.',
  },
  {
    id: 'mob-4',
    domainId: 'mobile-dev',
    domainTitle: 'Mobile App Development',
    numberInDomain: 4,
    title: 'React Native Fundamentals & Component Architecture',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Leverage your React web skills on native mobile platforms with React Native and Expo. Understand core components, styling with StyleSheet, and React Navigation.',
    keyTopics: ['React Native Bridge & New Architecture (Fabric/TurboModules)', 'Core Components: View, Text, Image, FlatList, Touchable', 'Declarative Mobile Navigation with React Navigation', 'Expo CLI Workflow, Testing on Physical Devices via QR Codes'],
    projectOutcome: 'Build an interactive social feed mobile application with infinite scrolling and image uploads.',
    prerequisites: 'Solid React.js foundation.',
    targetAudience: 'Web developers transitioning into mobile app engineering.',
  },
  {
    id: 'mob-5',
    domainId: 'mobile-dev',
    domainTitle: 'Mobile App Development',
    numberInDomain: 5,
    title: 'Advanced Native Features: Camera, GPS, Push Notifications & Offline Storage',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Unlock device hardware capabilities in your mobile apps. Implement camera capture, GPS geolocation mapping, background tasks, Firebase Cloud Messaging push alerts, and SQLite.',
    keyTopics: ['Device Hardware Permissions & Camera APIs', 'Geolocation, Live GPS Tracking & Map Integrations', 'Push Notifications with Firebase Cloud Messaging (FCM)', 'Offline-First SQLite / WatermelonDB Data Synchronization'],
    projectOutcome: 'Engineer a location-aware delivery tracking app with live map markers and real-time push alerts.',
    prerequisites: 'Intermediate Flutter or React Native development experience.',
    targetAudience: 'Mobile engineers building sophisticated, hardware-integrated commercial applications.',
  },
  {
    id: 'mob-6',
    domainId: 'mobile-dev',
    domainTitle: 'Mobile App Development',
    numberInDomain: 6,
    title: 'App Store & Play Store Deployment, CI/CD for Mobile',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Take your app to the world. Learn code signing, certificates, provisioning profiles, Android App Bundles (.aab), Fastlane automation, and automated test deployments.',
    keyTopics: ['Android Keystore Signing & Google Play Console Setup', 'Apple Developer Certificates, Provisioning & TestFlight', 'Automated Mobile Builds with Fastlane & GitHub Actions', 'Crash Reporting & Performance Monitoring (Firebase Crashlytics)'],
    projectOutcome: 'Configure an automated CI/CD pipeline that compiles, signs, and delivers beta builds to TestFlight & Google Play Internal Testing.',
    prerequisites: 'Completed mobile application ready for release.',
    targetAudience: 'Senior mobile developers and technical leads ready to publish to commercial app stores.',
  },

  // ==================== DOMAIN 8: UI / UX DESIGN & PRODUCT THINKING ====================
  {
    id: 'ui-1',
    domainId: 'ui-ux',
    domainTitle: 'UI / UX Design & Product Thinking',
    numberInDomain: 1,
    title: 'Design Thinking, User Research & Persona Creation',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Empathize with users before drawing a single pixel. Master the 5 stages of Design Thinking, conduct qualitative user interviews, and construct actionable user personas and journey maps.',
    keyTopics: ['The 5 Stages of Design Thinking (Empathize, Define, Ideate, Prototype, Test)', 'Conducting Generative User Interviews & Surveys', 'Synthesizing Research with Empathy Maps & Personas', 'Mapping As-Is and To-Be Customer Journey Maps'],
    projectOutcome: 'Deliver a comprehensive user research report and journey map solving an authentic user problem.',
    prerequisites: 'Open mindset and empathy. No design software knowledge required.',
    targetAudience: 'Product managers, aspiring UX designers, and engineers who care about user experience.',
  },
  {
    id: 'ui-2',
    domainId: 'ui-ux',
    domainTitle: 'UI / UX Design & Product Thinking',
    numberInDomain: 2,
    title: 'Wireframing, Layouts & Information Architecture in Figma',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Translate user insights into structured visual blueprints. Learn information architecture, card sorting, low-fidelity wireframing, and Figma interface navigation.',
    keyTopics: ['Information Architecture & Sitemap Hierarchy', 'Low-Fidelity Paper to Digital Wireframing in Figma', 'Grid Systems, Spacing Scales & Visual Hierarchy', 'User Flow Diagramming & Content Mapping'],
    projectOutcome: 'Create a complete low-fidelity wireframe clickable prototype for a multi-step digital product.',
    prerequisites: 'Basic computer literacy.',
    targetAudience: 'Anyone wanting to master Figma and interface structuring.',
  },
  {
    id: 'ui-3',
    domainId: 'ui-ux',
    domainTitle: 'UI / UX Design & Product Thinking',
    numberInDomain: 3,
    title: 'Interactive Prototyping, Micro-Interactions & Figma Components',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Bring static designs to life with smart animations. Master Figma master components, component variants, smart animate transitions, and micro-interaction states.',
    keyTopics: ['Master Components, Instances & Overrides', 'Component Variants & Interactive Component States (Hover, Active, Disabled)', 'Smart Animate Transitions & Realistic Screen Easing', 'Prototyping Complex Drag, Scroll, and Modal Behaviors'],
    projectOutcome: 'Produce a high-fidelity interactive mobile prototype with realistic micro-animations and page transitions.',
    prerequisites: 'Figma basics and wireframing understanding.',
    targetAudience: 'UI designers aiming to build persuasive, presentation-ready prototypes.',
  },
  {
    id: 'ui-4',
    domainId: 'ui-ux',
    domainTitle: 'UI / UX Design & Product Thinking',
    numberInDomain: 4,
    title: 'Design Systems: Tokens, Auto-Layout & Component Libraries',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Learn how world-class tech companies build scalable design systems. Master Figma Auto-Layout 5.0, design tokens (colors, typography, spacing), and component libraries.',
    keyTopics: ['Design Tokens Architecture (Global, Semantic, Component Tokens)', 'Auto-Layout Mastery: Resizing, Constraints & Nested Frames', 'Building Reusable Atoms, Molecules & Organisms (Atomic Design)', 'Documenting Component Guidelines for Cross-Functional Teams'],
    projectOutcome: 'Build and publish a comprehensive, scalable design system library in Figma with full Auto-Layout.',
    prerequisites: 'Proficiency in Figma components and UI layout.',
    targetAudience: 'Product designers and design system engineers building scalable design foundations.',
  },
  {
    id: 'ui-5',
    domainId: 'ui-ux',
    domainTitle: 'UI / UX Design & Product Thinking',
    numberInDomain: 5,
    title: 'Usability Testing, Heuristic Evaluation & UX Audits',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Evaluate digital products like an expert UX researcher. Conduct Nielsen Norman Group 10 heuristic evaluations, run moderated usability tests, and calculate usability metrics (SUS).',
    keyTopics: ['Nielsen Norman 10 Usability Heuristics Deep-Dive', 'Planning & Moderating Usability Test Sessions', 'Task Completion Rates, Time-on-Task & System Usability Scale (SUS)', 'Conducting Commercial Product UX Audits & Redesign Proposals'],
    projectOutcome: 'Execute a full UX audit of a live consumer application and deliver an evidence-backed redesign proposal.',
    prerequisites: 'Strong UI/UX design knowledge.',
    targetAudience: 'UX researchers, product designers, and product leaders looking to measure UX impact.',
  },
  {
    id: 'ui-6',
    domainId: 'ui-ux',
    domainTitle: 'UI / UX Design & Product Thinking',
    numberInDomain: 6,
    title: 'Product Strategy, Metrics (A/B Testing) & Design Handoff',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Bridge design with business outcomes and engineering implementation. Learn North Star metrics, A/B testing methodologies, Figma-to-code design tokens, and engineering handoff.',
    keyTopics: ['Product Growth Metrics & North Star Frameworks', 'A/B Testing Hypothesis Formulation & Statistical Significance', 'Pixel-Perfect Developer Handoff & Redline Specs in Figma', 'Translating Figma Tokens into Code (CSS Variables / Tailwind Config)'],
    projectOutcome: 'Formulate an end-to-end product strategy document, A/B test plan, and engineering-ready handoff package.',
    prerequisites: 'Advanced UI/UX design and product fundamentals.',
    targetAudience: 'Senior designers, design leads, and product managers ready for leadership responsibilities.',
  },

  // ==================== DOMAIN 9: BLOCKCHAIN & WEB3 ====================
  {
    id: 'chain-1',
    domainId: 'blockchain',
    domainTitle: 'Blockchain & Web3',
    numberInDomain: 1,
    title: 'Blockchain Fundamentals: Cryptography, Consensus & Ledgers',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Understand the math and mechanics behind decentralized systems: SHA-256 hashing, asymmetric cryptography, public/private key pairs, Merkle trees, and consensus mechanisms.',
    keyTopics: ['Cryptographic Hash Functions & Asymmetric Key Cryptography', 'Distributed Ledgers vs Centralized Databases', 'Consensus Mechanisms: Proof of Work (PoW) vs Proof of Stake (PoS)', 'Block Architecture, Nonces, Difficulty & Merkle Trees'],
    projectOutcome: 'Build a lightweight blockchain simulator from scratch in Python or JavaScript.',
    prerequisites: 'Basic programming concept familiarity.',
    targetAudience: 'Students and software engineers intrigued by the cryptographic foundation of Web3.',
  },
  {
    id: 'chain-2',
    domainId: 'blockchain',
    domainTitle: 'Blockchain & Web3',
    numberInDomain: 2,
    title: 'Intro to Ethereum, Wallets (MetaMask) & Web3 Ecosystem',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Enter the Ethereum ecosystem. Learn EVM (Ethereum Virtual Machine) concepts, gas fees, seed phrases, MetaMask setup, testnet faucets, and block explorer analysis (Etherscan).',
    keyTopics: ['Ethereum Virtual Machine (EVM) Architecture & Gas Economics', 'Wallet Security: Seed Phrases, Private Keys & MetaMask Configuration', 'Interacting with Ethereum Testnets (Sepolia / Holesky)', 'Analyzing Transactions, Contracts & Events on Etherscan'],
    projectOutcome: 'Set up an active Web3 wallet, fund it on testnet, and conduct verifiable transactions recorded on-chain.',
    prerequisites: 'Basic understanding of blockchain concepts.',
    targetAudience: 'Developers and enthusiasts ready to interact with live decentralized networks.',
  },
  {
    id: 'chain-3',
    domainId: 'blockchain',
    domainTitle: 'Blockchain & Web3',
    numberInDomain: 3,
    title: 'Smart Contract Development with Solidity & Remix',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Write, test, and deploy smart contracts on Ethereum using Solidity and Remix IDE. Understand contract structures, data types, mappings, function modifiers, and inheritance.',
    keyTopics: ['Solidity Syntax, Value Types, Mappings & Structs', 'State Variables, Visibility Modifiers & Function Decorators', 'Events, Error Handling (require/revert) & Custom Modifiers', 'Compiling and Deploying Contracts via Remix to Testnets'],
    projectOutcome: 'Develop, deploy, and verify a decentralized voting or crowdfunding smart contract on a public testnet.',
    prerequisites: 'Comfortable with object-oriented programming concepts.',
    targetAudience: 'Developers wanting to become Solidity smart contract engineers.',
  },
  {
    id: 'chain-4',
    domainId: 'blockchain',
    domainTitle: 'Blockchain & Web3',
    numberInDomain: 4,
    title: 'Building DApps with Ethers.js / Web3.js & React',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Connect modern React web frontends to deployed smart contracts. Use Ethers.js to authenticate wallets, call read/write contract functions, and listen for live blockchain events.',
    keyTopics: ['Connecting React Apps to MetaMask via Ethers.js / Wagmi', 'Reading Smart Contract State & Sending Transaction Calls', 'Handling Pending Transactions, Gas Estimation & Confirmations', 'Listening for Contract Events & Updating UI State in Real Time'],
    projectOutcome: 'Build an interactive decentralized application (DApp) allowing users to stake tokens and view live on-chain balances.',
    prerequisites: 'React.js and basic Solidity contract understanding.',
    targetAudience: 'Frontend developers wanting to transition into full-stack Web3 application builders.',
  },
  {
    id: 'chain-5',
    domainId: 'blockchain',
    domainTitle: 'Blockchain & Web3',
    numberInDomain: 5,
    title: 'DeFi Protocol Architecture & Token Standards (ERC-20, ERC-721, ERC-1155)',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Master the tokens that power Web3: fungible tokens (ERC-20), non-fungible tokens (ERC-721/1155), decentralized exchanges (DEXs), automated market makers (AMMs), and liquidity pools.',
    keyTopics: ['ERC-20 Token Standard & OpenZeppelin Implementation', 'ERC-721 / ERC-1155 NFT Minting & IPFS Metadata Storage', 'Automated Market Maker (AMM) Math (x * y = k formula)', 'Staking Pools, Yield Generation & Liquidity Mechanics'],
    projectOutcome: 'Deploy a custom ERC-20 token and an NFT minting platform with decentralized IPFS metadata hosting.',
    prerequisites: 'Solid experience with Solidity and contract deployments.',
    targetAudience: 'Web3 developers aiming to build protocols, DeFi platforms, or NFT ecosystems.',
  },
  {
    id: 'chain-6',
    domainId: 'blockchain',
    domainTitle: 'Blockchain & Web3',
    numberInDomain: 6,
    title: 'Smart Contract Security, Auditing & Gas Optimization',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Protect millions in decentralized value. Analyze famous smart contract vulnerabilities (Reentrancy, Flash Loans, Frontrunning), use automated security tools (Slither/Mythril), and optimize gas.',
    keyTopics: ['Reentrancy Attacks & Checks-Effects-Interactions Pattern', 'Integer Overflow, Frontrunning & Flash Loan Exploit Mechanics', 'Automated Vulnerability Scanning with Slither and Mythril', 'Solidity Gas Optimization Techniques & Assembly (Yul) Basics'],
    projectOutcome: 'Audit and exploit a deliberately vulnerable smart contract challenge (Capture The Flag) and produce a formal security audit report.',
    prerequisites: 'Advanced Solidity development and Ethereum understanding.',
    targetAudience: 'Smart contract developers and security researchers wanting to specialize in Web3 auditing.',
  },

  // ==================== DOMAIN 10: IOT & EMBEDDED SYSTEMS ====================
  {
    id: 'iot-1',
    domainId: 'iot-embedded',
    domainTitle: 'Internet of Things (IoT) & Embedded Systems',
    numberInDomain: 1,
    title: 'Intro to Embedded Systems: C/C++ on Arduino',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Get hands-on with real electronics. Learn embedded C/C++ programming on Arduino microcontrollers, digital and analog I/O pins, pulse width modulation (PWM), and serial communication.',
    keyTopics: ['Microcontroller Architecture & Arduino IDE Setup', 'Digital I/O: Controlling LEDs, Relays & Pushbuttons', 'Analog Reading, Potentiometers & PWM Duty Cycles', 'Serial Communication for Telemetry & Debugging'],
    projectOutcome: 'Build an automated smart home lighting and climate indicator circuit with serial monitoring.',
    prerequisites: 'Curiosity about physical computing and hardware.',
    targetAudience: 'Electrical, electronics, mechanical, and computer science students interested in embedded hardware.',
  },
  {
    id: 'iot-2',
    domainId: 'iot-embedded',
    domainTitle: 'Internet of Things (IoT) & Embedded Systems',
    numberInDomain: 2,
    title: 'Sensors, Actuators & Circuit Basics',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Interface microcontrollers with the physical world. Connect ultrasonic distance sensors, temperature/humidity sensors (DHT11/22), servo motors, stepper drivers, and LCD displays.',
    keyTopics: ['Sensor Interfacing: DHT11/22, Ultrasonic, LDR, PIR', 'Actuators: DC Motors, Servos, Stepper Motor Drivers', 'I2C and SPI Communication Protocols for Hardware Modules', 'Breadboard Prototyping, Power Distribution & Circuit Protection'],
    projectOutcome: 'Build an automated obstacle avoidance alert system with sensor displays and audio-visual alarms.',
    prerequisites: 'Basic knowledge of Arduino or embedded C.',
    targetAudience: 'Makers, robotics students, and IoT enthusiasts building physical prototypes.',
  },
  {
    id: 'iot-3',
    domainId: 'iot-embedded',
    domainTitle: 'Internet of Things (IoT) & Embedded Systems',
    numberInDomain: 3,
    title: 'ESP32 / ESP8266 IoT Projects with Wi-Fi & Bluetooth',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Add connectivity to embedded hardware with the dual-core ESP32 chip. Master Wi-Fi station and access point modes, Bluetooth Low Energy (BLE) services, and embedded web servers.',
    keyTopics: ['ESP32 Dual-Core Architecture & Pinout Specifications', 'Wi-Fi Connection Handling, Auto-Reconnect & Captive Portals', 'Building an Embedded Asynchronous Web Server on ESP32', 'Bluetooth Low Energy (BLE) Client/Server Communication'],
    projectOutcome: 'Create a Wi-Fi-enabled smart energy monitor accessible via a smartphone web browser.',
    prerequisites: 'Experience with Arduino or C/C++ programming.',
    targetAudience: 'Developers wanting to build connected IoT consumer and industrial devices.',
  },
  {
    id: 'iot-4',
    domainId: 'iot-embedded',
    domainTitle: 'Internet of Things (IoT) & Embedded Systems',
    numberInDomain: 4,
    title: 'IoT Communication Protocols: MQTT, HTTP & WebSockets',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Learn the messaging protocols of modern smart infrastructure. Implement lightweight publish/subscribe messaging using MQTT (Mosquitto/HiveMQ), REST API callbacks, and WebSockets.',
    keyTopics: ['MQTT Architecture: Brokers, Topics, QoS Levels & Payloads', 'Implementing MQTT Clients on Microcontrollers', 'HTTP REST vs MQTT: Bandwidth & Power Consumption Comparison', 'Real-Time Bi-Directional Telemetry via WebSockets'],
    projectOutcome: 'Develop an environmental telemetry station that publishes temperature and air quality metrics over MQTT to a live dashboard.',
    prerequisites: 'Working knowledge of ESP32 / Arduino and networking basics.',
    targetAudience: 'Engineers designing scalable data communication pipelines for connected devices.',
  },
  {
    id: 'iot-5',
    domainId: 'iot-embedded',
    domainTitle: 'Internet of Things (IoT) & Embedded Systems',
    numberInDomain: 5,
    title: 'Raspberry Pi: Linux Embedded, Python & GPIO Projects',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Step up from microcontrollers to single-board computers. Run headless Linux on Raspberry Pi, interact with 40-pin GPIOs via Python, stream Pi Camera video, and run edge inference.',
    keyTopics: ['Headless Raspberry Pi OS Setup & Remote SSH Configuration', 'Interfacing 40-pin GPIO via Python (RPi.GPIO / gpiozero)', 'Connecting Pi Camera & Video Stream Processing', 'Edge Computing: Running Lightweight Machine Learning on Pi'],
    projectOutcome: 'Build an edge-based smart surveillance monitor with motion detection, video capture, and automated notifications.',
    prerequisites: 'Python knowledge and Linux basics.',
    targetAudience: 'Engineers wanting to build edge computing and computer-vision powered hardware appliances.',
  },
  {
    id: 'iot-6',
    domainId: 'iot-embedded',
    domainTitle: 'Internet of Things (IoT) & Embedded Systems',
    numberInDomain: 6,
    title: 'End-to-End IoT: Edge Device to AWS IoT Core / Azure IoT Hub Dashboard',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Build enterprise-grade IoT architectures. Secure devices with X.509 certificates, connect to AWS IoT Core / Azure IoT Hub, define routing rules, and visualize live data in cloud dashboards.',
    keyTopics: ['X.509 Certificate-Based Device Authentication & TLS Encryption', 'AWS IoT Core Device Shadows & Message Routing Rules', 'Storing Time-Series Telemetry in Cloud Databases (DynamoDB/InfluxDB)', 'Building Live Telemetry Analytics Dashboards in Grafana / CloudWatch'],
    projectOutcome: 'Deploy an enterprise industrial monitoring system from physical sensor to an interactive AWS cloud monitoring dashboard.',
    prerequisites: 'Strong IoT hardware knowledge and basic cloud familiarity.',
    targetAudience: 'IoT architects and engineers building commercial and smart-city hardware solutions.',
  },

  // ==================== DOMAIN 11: SOFTWARE TESTING & AUTOMATION ====================
  {
    id: 'test-1',
    domainId: 'software-testing',
    domainTitle: 'Software Testing & Automation',
    numberInDomain: 1,
    title: 'Software Testing Fundamentals: Manual Testing & Test Case Design',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Build a rigorous quality mindset. Master the Software Testing Life Cycle (STLC), black-box test design techniques (Boundary Value Analysis, Equivalence Partitioning), and bug reporting.',
    keyTopics: ['Software Testing Life Cycle (STLC) & Defect Life Cycle', 'Equivalence Class Partitioning & Boundary Value Analysis', 'Writing Comprehensive Test Cases & Acceptance Criteria', 'Bug Tracking, Severity vs Priority & Jira Workflows'],
    projectOutcome: 'Author a complete test plan, test suite of 30+ test cases, and formal defect reports for an e-commerce platform.',
    prerequisites: 'Basic understanding of software applications. No programming required.',
    targetAudience: 'Students and beginners aiming to launch careers as Quality Assurance (QA) engineers.',
  },
  {
    id: 'test-2',
    domainId: 'software-testing',
    domainTitle: 'Software Testing & Automation',
    numberInDomain: 2,
    title: 'API Testing with Postman & Newman',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Validate backend logic without touching the UI. Master HTTP request methods, environment variables, authentication headers, JavaScript assertions in Postman, and Newman CLI.',
    keyTopics: ['HTTP Methods (GET, POST, PUT, DELETE) & Status Codes', 'Postman Collections, Environments & Dynamic Variables', 'Writing Automated Test Assertions in JavaScript in Postman', 'Executing Collections via Newman CLI for Automated Reports'],
    projectOutcome: 'Build an automated regression test suite covering 20+ API endpoints with status and schema assertions.',
    prerequisites: 'Basic understanding of web and API concepts.',
    targetAudience: 'QA engineers and developers wanting to ensure robust backend reliability.',
  },
  {
    id: 'test-3',
    domainId: 'software-testing',
    domainTitle: 'Software Testing & Automation',
    numberInDomain: 3,
    title: 'Test Automation with Selenium WebDriver & Java/Python',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Automate browser testing with industry-standard Selenium WebDriver. Master robust element locators (XPath, CSS), implicit/explicit waits, and Page Object Model (POM) architecture.',
    keyTopics: ['Selenium WebDriver Architecture & Browser Drivers', 'Advanced Element Locators (Dynamic XPath & CSS Selectors)', 'Handling Dynamic Elements with Explicit & Fluent Waits', 'Architecting Page Object Model (POM) Test Frameworks'],
    projectOutcome: 'Engineer a scalable Selenium test automation framework that automates an entire end-to-end checkout flow.',
    prerequisites: 'Basic knowledge of Java or Python.',
    targetAudience: 'Manual testers looking to transition into automation engineering.',
  },
  {
    id: 'test-4',
    domainId: 'software-testing',
    domainTitle: 'Software Testing & Automation',
    numberInDomain: 4,
    title: 'Modern Web Automation with Cypress / Playwright',
    level: 'Intermediate',
    duration: '2 Days (16 Hours)',
    description: 'Learn modern, lightning-fast end-to-end testing with Cypress and Playwright. Experience auto-waiting, network stubbing, cross-browser testing (Chromium, Firefox, WebKit), and video artifacts.',
    keyTopics: ['Cypress & Playwright Modern Architectures vs Selenium', 'Auto-Waiting, Time-Travel Debugging & Visual Snapshots', 'Network Mocking, Request Interception & API Spying', 'Cross-Browser Parallel Execution in Headless Mode'],
    projectOutcome: 'Build a blazing-fast Playwright end-to-end test suite with visual regression checking and video recordings.',
    prerequisites: 'JavaScript / TypeScript familiarity.',
    targetAudience: 'Frontend developers and modern QA engineers seeking next-generation test tools.',
  },
  {
    id: 'test-5',
    domainId: 'software-testing',
    domainTitle: 'Software Testing & Automation',
    numberInDomain: 5,
    title: 'Mobile App Testing with Appium',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Automate testing across native and hybrid mobile applications on Android and iOS using Appium. Inspect mobile UI hierarchies, automate gestures, and run tests on emulators and real devices.',
    keyTopics: ['Appium Architecture & W3C Mobile WebDriver Protocol', 'Inspecting Mobile Elements with Appium Inspector', 'Automating Gestures: Tap, Swipe, Pinch, Drag & Scroll', 'Running Tests Across Android Emulators & Physical Hardware'],
    projectOutcome: 'Develop an automated mobile test suite that validates login, navigation, and form submissions on Android.',
    prerequisites: 'Experience with Selenium or object-oriented test automation.',
    targetAudience: 'Automation engineers specializing in mobile application quality.',
  },
  {
    id: 'test-6',
    domainId: 'software-testing',
    domainTitle: 'Software Testing & Automation',
    numberInDomain: 6,
    title: 'Performance & Load Testing with JMeter / k6 + CI/CD Integration',
    level: 'Advanced',
    duration: '2-3 Days (16-24 Hours)',
    description: 'Ensure systems can withstand viral traffic spikes. Design realistic load profiles in Apache JMeter and k6, monitor server latency and throughput, and integrate performance gates into CI/CD.',
    keyTopics: ['Performance Testing Metrics: Latency, Throughput, Percentiles, Error Rate', 'Creating Realistic User Scenarios in Apache JMeter & k6 (JavaScript)', 'Stress Testing, Spike Testing & Endurance Soak Tests', 'Integrating Performance Quality Gates into GitHub Actions CI/CD'],
    projectOutcome: 'Simulate 5,000 concurrent users against a web API, diagnose server bottlenecks, and deliver an optimization report.',
    prerequisites: 'Strong API and backend understanding.',
    targetAudience: 'Performance engineers, DevOps engineers, and senior QA specialists.',
  },
];

export const FOUNDATION_WORKSHOPS: FoundationWorkshop[] = [
  {
    id: 'fnd-1',
    number: 1,
    title: 'SQL from Scratch: Queries, Joins, Indexing & Database Design',
    tagline: 'The universal language of data and enterprise backends',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Whether you enter AI, Full Stack, Data Science, or DevOps, SQL is essential. Master relational schemas, multi-table joins, subqueries, aggregations, window functions, and performance indexing.',
    keyTopics: [
      'Relational Database Modeling & Normalization (1NF, 2NF, 3NF)',
      'CRUD Operations, Filtering & Multi-Table INNER / LEFT / FULL JOINs',
      'Aggregate Functions, GROUP BY, HAVING & Subqueries',
      'B-Tree Indexing, Query Optimization & EXPLAIN Execution Plans',
    ],
    handsOnOutcome: 'Design, populate, and query an enterprise database schema with complex analytical reporting queries.',
  },
  {
    id: 'fnd-2',
    number: 2,
    title: 'Data Structures & Algorithms: The Practical Guide (in Python/Java)',
    tagline: 'Core problem-solving foundation for product company technical interviews',
    duration: '2 Days (16 Hours)',
    description: 'Demystify Big-O complexity analysis, arrays, linked lists, stacks, queues, hash maps, trees, and graphs. Learn practical problem patterns that recur across top software engineering interviews.',
    keyTopics: [
      'Time & Space Complexity (Big-O Notation Deep-Dive)',
      'Essential Data Structures: Arrays, Hash Maps, Stacks & Queues',
      'Recursion, Binary Trees & Breadth/Depth-First Search (BFS/DFS)',
      'Two-Pointer & Sliding Window Patterns for Coding Interviews',
    ],
    handsOnOutcome: 'Solve 20+ curated LeetCode-style algorithmic challenges live with guided time/space optimization.',
  },
  {
    id: 'fnd-3',
    number: 3,
    title: 'Problem Solving, Git/GitHub & Technical Interview Readiness',
    tagline: 'Bridging the critical gap between academic knowledge and industry employment',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master professional version control with Git branching, pull requests, merge conflict resolution, algorithmic problem-solving frameworks, resume portfolio curation, and mock technical whiteboard rounds.',
    keyTopics: [
      'Git Fundamentals: Commits, Branching, Rebasing & Resolving Merge Conflicts',
      'GitHub Workflows: Pull Requests, Code Reviews & Markdown Readmes',
      'Systematic Problem-Solving Frameworks for Whiteboard Challenges',
      'Building an Impressive Developer GitHub Portfolio & Resume Tuning',
    ],
    handsOnOutcome: 'Publish a polished, review-ready GitHub repository with branching history, professional README, and live project documentation.',
  },
];

export const WORKSHOP_PROGRESSION = [
  {
    stage: '01',
    name: 'DISCOVER',
    subtitle: 'Explore Fundamentals',
    description: 'Understand the industry landscape, emerging trends, real-world case studies, and career paths across the domain.',
    badge: 'Foundation',
  },
  {
    stage: '02',
    name: 'LEARN',
    subtitle: 'Core Architecture',
    description: 'Master foundational syntax, software patterns, tools, and theoretical principles with live guided mentor demonstrations.',
    badge: 'Core Concepts',
  },
  {
    stage: '03',
    name: 'BUILD',
    subtitle: 'Hands-On Labs',
    description: 'Write real code and build functioning modules in interactive, milestone-driven laboratory environments.',
    badge: 'Live Coding',
  },
  {
    stage: '04',
    name: 'APPLY',
    subtitle: 'Real-World Integration',
    description: 'Connect databases, external APIs, cloud services, and handle real-world edge cases and debugging.',
    badge: 'Production Ready',
  },
  {
    stage: '05',
    name: 'CREATE',
    subtitle: 'Portfolio Artifacts',
    description: 'Complete deployable capstone projects with verifiable GitHub repositories and verified credentials for interviews.',
    badge: 'Career Launch',
  },
];

export const WORKSHOP_VIDEOS: WorkshopVideoItem[] = [
  {
    id: 'wk-vid-1',
    title: 'Independence Day Celebration',
    collegeOrEvent: 'Community & Student Outreach',
    aspectRatio: 'landscape',
    src: '/workshops/videos/workshop_video_1.mp4',
    poster: '/workshops/posters/poster_1.jpg',
    caption: 'A special Independence Day celebration with children, bringing the CSL community together through meaningful interactions and a stationery donation initiative.',
    tag: 'Auditorium & Lab Session',
  },
  {
    id: 'wk-vid-2',
    title: 'Ethiraj College for Women Workshop Session',
    collegeOrEvent: 'Ethiraj College for Women, Chennai',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_2.mp4',
    poster: '/workshops/posters/poster_2.jpg',
    caption: 'Empowering students with industry-standard development workflows and practical guidance.',
    tag: 'Campus Workshop',
  },
  {
    id: 'wk-vid-3',
    title: 'Interactive Hands-On Seminar & Practical Coding',
    collegeOrEvent: 'Engineering College Campus',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_3.mp4',
    poster: '/workshops/posters/poster_3.jpg',
    caption: 'Real-time student engagement, live debugging, and collaborative breakout sessions.',
    tag: 'Live Seminar',
  },
  {
    id: 'wk-vid-4',
    title: 'Real Learning Happens When You Participate',
    collegeOrEvent: 'Hands-On Tech Lab',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_4.mp4',
    poster: '/workshops/posters/poster_4.jpg',
    caption: 'Students actively writing code, deploying modules, and presenting working solutions.',
    tag: 'Interactive Lab',
  },
  {
    id: 'wk-vid-5',
    title: 'Bridging the Gap: Campus to Corporate Readiness',
    collegeOrEvent: 'Industry Technology Workshop',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_5.mp4',
    poster: '/workshops/posters/poster_5.jpg',
    caption: 'Industry mentors demystifying real-world corporate expectations, tools, and career pathways.',
    tag: 'Career Readiness',
  },
];

export const WHY_CHOOSE_WORKSHOPS = [
  {
    num: '01',
    title: '11 High-Demand Modern Industry Domains',
    description: 'From Generative AI and Cloud DevOps to Game Development and IoT, our syllabus covers the technologies leading global tech recruitment today.',
  },
  {
    num: '02',
    title: '100% Hands-On & Project-Centric Learning',
    description: 'Zero passive lecturing. Every single workshop session requires participants to write code, configure environments, and build functioning modules.',
  },
  {
    num: '03',
    title: 'Multi-Tiered Progression (Basic to Advanced)',
    description: 'Structured 3-tier difficulty pathways enable complete beginners to start smoothly, while advanced modules challenge experienced learners.',
  },
  {
    num: '04',
    title: 'Verified Certification & GitHub Portfolio Artifacts',
    description: 'Attendees walk away with verifiable completion credentials and clean GitHub code repositories ready to showcase in placements and job interviews.',
  },
  {
    num: '05',
    title: 'Tailored for College Campuses & Corporate Bootcamps',
    description: 'Modular 1-day to 3-day formats seamlessly align with academic semester calendars, symposiums, value-added courses, and enterprise team training.',
  },
];
