export type WorkshopLevel = 'Basic' | 'Intermediate' | 'Advanced';

export interface WorkshopItem {
  id: string;
  domainId: string;
  domainTitle: string;
  numberInDomain: number;
  title: string;
  level: WorkshopLevel;
  duration: string;
  description: string;
  keyTopics: string[];
  projectOutcome: string;
  prerequisites: string;
  targetAudience: string;
}

export interface WorkshopDomain {
  id: string;
  domainNumber: number;
  title: string;
  shortTitle: string;
  description: string;
  trending: boolean;
  tagline: string;
  iconName: string;
  colorScheme: {
    badge: string;
    border: string;
    gradient: string;
    accent: string;
  };
  levelsSummary: {
    basic: string;
    intermediate: string;
    advanced: string;
  };
}

export interface FoundationWorkshop {
  id: string;
  number: number;
  title: string;
  tagline: string;
  duration: string;
  description: string;
  keyTopics: string[];
  handsOnOutcome: string;
}

export interface WorkshopVideoItem {
  id: string;
  title: string;
  collegeOrEvent: string;
  aspectRatio: 'landscape' | 'portrait';
  src: string;
  poster: string;
  caption: string;
  tag: string;
}

export const WORKSHOP_DOMAINS: WorkshopDomain[] = [
  {
    id: 'ai-ml',
    domainNumber: 1,
    title: 'AI/ML with Automation',
    shortTitle: 'AI & Automation',
    trending: true,
    tagline: 'From Fundamental ML to LLMs, RAG & Autonomous Workflow Agents',
    description: 'Master practical artificial intelligence, predictive machine learning with scikit-learn, deep neural networks, RAG architectures, and AI agent workflows with LangChain & n8n.',
    iconName: 'Cpu',
    colorScheme: {
      badge: 'bg-amber-500/10 text-amber-700 border-amber-500/30',
      border: 'hover:border-amber-500/60',
      gradient: 'from-amber-500/15 via-orange-500/5 to-transparent',
      accent: 'text-amber-600',
    },
    levelsSummary: {
      basic: 'Python for AI & Introduction to ML with scikit-learn',
      intermediate: 'Deep Learning with Neural Networks & NLP Sentiment Analysis',
      advanced: 'Building LLM Apps with RAG & Autonomous AI Agents (LangChain/n8n)',
    },
  },
  {
    id: 'full-stack',
    domainNumber: 2,
    title: 'Full Stack Development with AI & Automation (Java/Python)',
    shortTitle: 'Full Stack with AI',
    trending: true,
    tagline: 'Modern Web Architectures, LLM Integration & Workflow Automation',
    description: 'Build enterprise-grade full-stack web applications in Java/Python, connect React interfaces to REST APIs, inject intelligent AI features, and automate backend operations.',
    iconName: 'Layers',
    colorScheme: {
      badge: 'bg-blue-500/10 text-blue-700 border-blue-500/30',
      border: 'hover:border-blue-500/60',
      gradient: 'from-blue-500/15 via-indigo-500/5 to-transparent',
      accent: 'text-blue-600',
    },
    levelsSummary: {
      basic: 'Web Fundamentals (HTML/CSS/JS) & First REST API (Spring Boot/Flask)',
      intermediate: 'Full-Stack React Apps & AI Features (Chatbots, Smart Search)',
      advanced: 'Workflow Automation with AI Agents & Cloud Microservices',
    },
  },
  {
    id: 'data-analyst',
    domainNumber: 3,
    title: 'Data Analyst with AI & Automation',
    shortTitle: 'Data Analyst',
    trending: true,
    tagline: 'Transform Raw Business Data into Automated Executive Intelligence',
    description: 'Master spreadsheet modeling, relational SQL analytics, interactive Power BI/Tableau dashboards, Python data cleaning scripts, and AI-assisted analytics pipelines.',
    iconName: 'BarChart3',
    colorScheme: {
      badge: 'bg-emerald-500/10 text-emerald-700 border-emerald-500/30',
      border: 'hover:border-emerald-500/60',
      gradient: 'from-emerald-500/15 via-teal-500/5 to-transparent',
      accent: 'text-emerald-600',
    },
    levelsSummary: {
      basic: 'Excel for Data Analysis & SQL for Business Analysts',
      intermediate: 'Interactive Dashboards (Power BI/Tableau) & Python Automation',
      advanced: 'AI-Assisted Analytics for Insights & Automated Reporting Pipelines',
    },
  },
  {
    id: 'data-science',
    domainNumber: 4,
    title: 'Data Science & Machine Learning',
    shortTitle: 'Data Science',
    trending: true,
    tagline: 'Statistical Modeling, Feature Engineering & Production MLOps',
    description: 'Master scientific computing with NumPy and Pandas, exploratory visualization, feature engineering, regression/classification/clustering algorithms, and time-series forecasting.',
    iconName: 'Database',
    colorScheme: {
      badge: 'bg-purple-500/10 text-purple-700 border-purple-500/30',
      border: 'hover:border-purple-500/60',
      gradient: 'from-purple-500/15 via-violet-500/5 to-transparent',
      accent: 'text-purple-600',
    },
    levelsSummary: {
      basic: 'NumPy/Pandas Data Handling & Matplotlib/Seaborn Visualization',
      intermediate: 'Feature Engineering & Supervised/Unsupervised Algorithms',
      advanced: 'Time-Series Forecasting & Model Deployment MLOps Basics',
    },
  },
  {
    id: 'cyber-security',
    domainNumber: 5,
    title: 'Cybersecurity & Ethical Hacking',
    shortTitle: 'Cybersecurity',
    trending: true,
    tagline: 'Hands-On Vulnerability Assessment, Network Defense & Forensics',
    description: 'Configure security labs in Kali Linux, scan networks with Nmap & Wireshark, exploit OWASP Top 10 vulnerabilities, and execute professional penetration testing and incident response.',
    iconName: 'ShieldCheck',
    colorScheme: {
      badge: 'bg-rose-500/10 text-rose-700 border-rose-500/30',
      border: 'hover:border-rose-500/60',
      gradient: 'from-rose-500/15 via-red-500/5 to-transparent',
      accent: 'text-rose-600',
    },
    levelsSummary: {
      basic: 'Networking & Security Fundamentals & Kali Linux Lab Setup',
      intermediate: 'Web App Security (OWASP Top 10) & Network Scanning (Nmap/Wireshark)',
      advanced: 'Penetration Testing Methodology & Incident Response / Forensics',
    },
  },
  {
    id: 'cloud-devops',
    domainNumber: 6,
    title: 'DevOps with AWS (AI & Automation Deployment)',
    shortTitle: 'DevOps & AWS',
    trending: true,
    tagline: 'Automate Infrastructure, Containerization & Production Cloud Workflows',
    description: 'Provision AWS infrastructure (EC2, S3, IAM), containerize apps with Docker, automate CI/CD with Jenkins and GitHub Actions, orchestrate with Kubernetes, and deploy AI models.',
    iconName: 'Cloud',
    colorScheme: {
      badge: 'bg-sky-500/10 text-sky-700 border-sky-500/30',
      border: 'hover:border-sky-500/60',
      gradient: 'from-sky-500/15 via-cyan-500/5 to-transparent',
      accent: 'text-sky-600',
    },
    levelsSummary: {
      basic: 'Linux, Git & GitHub Essentials & AWS Fundamentals (EC2/S3/IAM)',
      intermediate: 'Docker Containers & CI/CD Pipelines (Jenkins/GitHub Actions)',
      advanced: 'Kubernetes / Terraform IaC & Deploying AI Models on AWS with Monitoring',
    },
  },
  {
    id: 'mobile-dev',
    domainNumber: 7,
    title: 'Full Stack + Mobile Development',
    shortTitle: 'Mobile Apps',
    trending: false,
    tagline: 'Cross-Platform Native Experiences with Flutter & React Native',
    description: 'Build native mobile user interfaces with Flutter and React Native, connect cross-platform frontends to Firebase and cloud APIs, manage state, and deploy AI-enhanced mobile apps.',
    iconName: 'Smartphone',
    colorScheme: {
      badge: 'bg-teal-500/10 text-teal-700 border-teal-500/30',
      border: 'hover:border-teal-500/60',
      gradient: 'from-teal-500/15 via-emerald-500/5 to-transparent',
      accent: 'text-teal-600',
    },
    levelsSummary: {
      basic: 'Mobile App Basics (Flutter/React Native) & UI Building/Navigation',
      intermediate: 'Connecting Apps to APIs & Firebase with Authentication',
      advanced: 'App Store / Play Store Publishing & AI Features Integration',
    },
  },
  {
    id: 'software-testing',
    domainNumber: 8,
    title: 'Software Testing with Automation (Selenium)',
    shortTitle: 'QA & Automation',
    trending: false,
    tagline: 'Enterprise Quality Assurance, Selenium Frameworks & AI Testing',
    description: 'Master manual test case design, Agile STLC workflows, automated browser testing with Selenium WebDriver (Java/Python), REST API testing with Postman, and AI-powered QA tools.',
    iconName: 'CheckCircle2',
    colorScheme: {
      badge: 'bg-lime-600/10 text-lime-800 border-lime-600/30',
      border: 'hover:border-lime-600/60',
      gradient: 'from-lime-500/15 via-emerald-500/5 to-transparent',
      accent: 'text-lime-700',
    },
    levelsSummary: {
      basic: 'Manual Testing, Test Cases & Bug Reporting in Agile/STLC',
      intermediate: 'Selenium WebDriver (Java/Python) & TestNG / PyTest Frameworks',
      advanced: 'API Testing (Postman/REST Assured) & CI/CD AI-Powered Testing',
    },
  },
  {
    id: 'business-analyst',
    domainNumber: 9,
    title: 'Business Analyst',
    shortTitle: 'Business Analyst',
    trending: false,
    tagline: 'Requirements Engineering, Agile Delivery & Data-Driven Strategy',
    description: 'Bridge business objectives with technical solutions. Master BRD/FRD authoring, user story mapping, UML process modeling in Jira/Confluence, and SQL/Power BI analytics.',
    iconName: 'Briefcase',
    colorScheme: {
      badge: 'bg-amber-600/10 text-amber-800 border-amber-600/30',
      border: 'hover:border-amber-600/60',
      gradient: 'from-amber-500/15 via-yellow-500/5 to-transparent',
      accent: 'text-amber-700',
    },
    levelsSummary: {
      basic: 'BA Role, SDLC & Documentation (BRD, FRD, User Stories)',
      intermediate: 'Process Modeling (UML/BPMN) & Wireframing with Jira/Confluence',
      advanced: 'Data-Driven Decision Making (SQL/Power BI) & Stakeholder Capstone',
    },
  },
  {
    id: 'crm-cloud',
    domainNumber: 10,
    title: 'ServiceNow, Salesforce & CRM',
    shortTitle: 'CRM & Cloud Ops',
    trending: false,
    tagline: 'Enterprise Workflow Automation, Salesforce Admin & ServiceNow ITSM',
    description: 'Explore leading enterprise CRM and ITSM platforms. Learn Salesforce data models and flows, ServiceNow incident and service catalogs, Apex development, and system integrations.',
    iconName: 'Workflow',
    colorScheme: {
      badge: 'bg-cyan-600/10 text-cyan-800 border-cyan-600/30',
      border: 'hover:border-cyan-600/60',
      gradient: 'from-cyan-500/15 via-blue-500/5 to-transparent',
      accent: 'text-cyan-700',
    },
    levelsSummary: {
      basic: 'CRM Fundamentals & Salesforce Admin Basics (Objects, Fields, Users)',
      intermediate: 'Flows & Process Automation & ServiceNow ITSM (Incidents, Catalog)',
      advanced: 'Apex & Lightning Development with Integrations and Dashboards',
    },
  },
  {
    id: 'ui-ux',
    domainNumber: 11,
    title: 'UI/UX Design',
    shortTitle: 'UI/UX Design',
    trending: false,
    tagline: 'Human-Centered Product Design, Design Systems & Figma Prototyping',
    description: 'Learn visual hierarchy, typography, user research, and wireframing in Figma. Build scalable design systems, interactive prototypes, and test usability for web and mobile.',
    iconName: 'Palette',
    colorScheme: {
      badge: 'bg-fuchsia-500/10 text-fuchsia-700 border-fuchsia-500/30',
      border: 'hover:border-fuchsia-500/60',
      gradient: 'from-fuchsia-500/15 via-pink-500/5 to-transparent',
      accent: 'text-fuchsia-600',
    },
    levelsSummary: {
      basic: 'Design Principles, Color, Typography & Figma Fundamentals',
      intermediate: 'User Research, Wireframing & Prototyping Web/Mobile Apps',
      advanced: 'Design Systems, Accessibility, Usability Testing & Portfolio',
    },
  },
];

export const ALL_WORKSHOPS: WorkshopItem[] = [
  // ==================== DOMAIN 1: AI/ML with Automation ====================
  {
    id: 'aiml-1',
    domainId: 'ai-ml',
    domainTitle: 'AI/ML with Automation',
    numberInDomain: 1,
    title: 'Python for AI and Machine Learning',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master core Python programming, vector math with NumPy, and data manipulation with Pandas tailored for AI and ML pipelines.',
    keyTopics: ['Python Syntax for AI', 'NumPy Vectors & Matrices', 'Pandas DataFrames', 'Jupyter Lab Workflows'],
    projectOutcome: 'Build an automated dataset cleaning and statistical summarizer script.',
    prerequisites: 'Basic computer literacy. No prior coding experience required.',
    targetAudience: 'Students and beginners stepping into artificial intelligence.',
  },
  {
    id: 'aiml-2',
    domainId: 'ai-ml',
    domainTitle: 'AI/ML with Automation',
    numberInDomain: 2,
    title: 'Introduction to ML with scikit-learn',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Understand supervised and unsupervised machine learning fundamentals, data splits, and model training using scikit-learn.',
    keyTopics: ['Linear Regression', 'Decision Trees', 'Classification Metrics', 'scikit-learn Pipelines'],
    projectOutcome: 'Train and evaluate a customer churn or house price predictor model.',
    prerequisites: 'Basic Python syntax knowledge.',
    targetAudience: 'Engineering and science students learning practical ML.',
  },
  {
    id: 'aiml-3',
    domainId: 'ai-ml',
    domainTitle: 'AI/ML with Automation',
    numberInDomain: 3,
    title: 'Deep Learning and Neural Networks',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Explore neural network architectures, activation functions, backpropagation, and multi-layer perceptrons with PyTorch/TensorFlow.',
    keyTopics: ['Artificial Neural Networks', 'Loss Functions & Optimizers', 'PyTorch / TensorFlow Tensors', 'Overfitting & Dropout'],
    projectOutcome: 'Construct an image or digit classifier using a multi-layer deep neural network.',
    prerequisites: 'Introductory machine learning fundamentals.',
    targetAudience: 'Aspiring AI researchers and developers.',
  },
  {
    id: 'aiml-4',
    domainId: 'ai-ml',
    domainTitle: 'AI/ML with Automation',
    numberInDomain: 4,
    title: 'NLP: Text Classification and Sentiment Analysis',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Preprocess unstructured text, extract vector embeddings with TF-IDF and word2vec, and train sentiment classification models.',
    keyTopics: ['Tokenization & Stemming', 'TF-IDF & Word Embeddings', 'Sentiment Analysis', 'Text Classification Pipelines'],
    projectOutcome: 'Build a real-time sentiment analyzer for social media reviews.',
    prerequisites: 'Familiarity with Python and scikit-learn.',
    targetAudience: 'Developers interested in natural language processing.',
  },
  {
    id: 'aiml-5',
    domainId: 'ai-ml',
    domainTitle: 'AI/ML with Automation',
    numberInDomain: 5,
    title: 'Building LLM Apps with RAG',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Architect production Retrieval-Augmented Generation (RAG) pipelines connecting vector databases with large language models.',
    keyTopics: ['LLM APIs & Prompt Design', 'Vector Databases (Chroma/Pinecone)', 'Document Chunking & Embeddings', 'RAG Retrieval Architectures'],
    projectOutcome: 'Deploy an intelligent document Q&A assistant querying custom PDF knowledge bases.',
    prerequisites: 'Intermediate Python and REST API knowledge.',
    targetAudience: 'Senior students and developers building GenAI products.',
  },
  {
    id: 'aiml-6',
    domainId: 'ai-ml',
    domainTitle: 'AI/ML with Automation',
    numberInDomain: 6,
    title: 'AI Agents and Workflow Automation (LangChain / n8n)',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Build autonomous reasoning agents with LangChain, LangGraph, and visual automation tools like n8n that execute actions via tools and APIs.',
    keyTopics: ['Agentic Reasoning Frameworks', 'LangChain Tools & Memory', 'n8n Workflow Automation', 'Multi-Agent Execution'],
    projectOutcome: 'Create an autonomous research agent that searches the web, summarizes data, and drafts emails.',
    prerequisites: 'Experience with LLMs and API integrations.',
    targetAudience: 'Engineers designing automated intelligent workflows.',
  },

  // ==================== DOMAIN 2: Full Stack Development with AI & Automation ====================
  {
    id: 'fs-1',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development with AI & Automation (Java/Python)',
    numberInDomain: 1,
    title: 'Web Fundamentals: HTML, CSS and JavaScript',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master core front-end building blocks: semantic HTML5, modern responsive CSS layouts, and interactive JavaScript DOM manipulation.',
    keyTopics: ['HTML5 Semantic Structure', 'CSS Flexbox & Grid', 'JavaScript Events & DOM', 'Responsive Mobile Layouts'],
    projectOutcome: 'Build an interactive responsive portfolio website from scratch.',
    prerequisites: 'No prior programming experience required.',
    targetAudience: 'Beginner developers starting web development.',
  },
  {
    id: 'fs-2',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development with AI & Automation (Java/Python)',
    numberInDomain: 2,
    title: 'Build Your First REST API (Spring Boot / Flask)',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Design and implement structured backend REST APIs in Spring Boot (Java) or Flask/FastAPI (Python) with HTTP routing and JSON responses.',
    keyTopics: ['REST Architecture Principles', 'Spring Boot / Flask Routing', 'Request Handling & JSON', 'Testing with Postman'],
    projectOutcome: 'Develop and test a CRUD REST API for a task management application.',
    prerequisites: 'Basic Java or Python syntax.',
    targetAudience: 'Students learning backend web services.',
  },
  {
    id: 'fs-3',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development with AI & Automation (Java/Python)',
    numberInDomain: 3,
    title: 'Full-Stack App with React and Database',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Connect a dynamic React frontend to a relational PostgreSQL/MySQL or MongoDB database via asynchronous backend API endpoints.',
    keyTopics: ['React Hooks & Component State', 'Fetching REST Endpoints', 'SQL / MongoDB Integration', 'Full-Stack Data Flow'],
    projectOutcome: 'Deliver a functioning full-stack web application with database persistence.',
    prerequisites: 'Basic JavaScript and REST API understanding.',
    targetAudience: 'Developers seeking full-stack integration expertise.',
  },
  {
    id: 'fs-4',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development with AI & Automation (Java/Python)',
    numberInDomain: 4,
    title: 'Adding AI Features (Chatbot, Smart Search) with LLM APIs',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Augment traditional web applications with generative AI capabilities: conversational chatbots, smart semantic search, and auto-summaries.',
    keyTopics: ['OpenAI / Gemini SDK Integration', 'Chatbot UI State in React', 'Semantic Vector Search', 'Token Management & Security'],
    projectOutcome: 'Incorporate a conversational AI assistant directly into a React web app.',
    prerequisites: 'React and backend API foundations.',
    targetAudience: 'Web engineers modernizing applications with AI.',
  },
  {
    id: 'fs-5',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development with AI & Automation (Java/Python)',
    numberInDomain: 5,
    title: 'Automating Workflows with AI Agents',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Build backend autonomous agent services that process webhooks, extract structured information from documents, and trigger database updates.',
    keyTopics: ['Automated Background Jobs', 'AI Webhook Processors', 'Structured Data Extraction', 'Function Calling & Tool Use'],
    projectOutcome: 'Create an automated customer invoice parser and database synchronization agent.',
    prerequisites: 'Full-stack development and API knowledge.',
    targetAudience: 'Developers building AI-powered operational backends.',
  },
  {
    id: 'fs-6',
    domainId: 'full-stack',
    domainTitle: 'Full Stack Development with AI & Automation (Java/Python)',
    numberInDomain: 6,
    title: 'Microservices, Authentication and Deployment',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Decompose monolithic backends into secure microservices with JWT/OAuth2 authentication, Docker containers, and cloud deployment.',
    keyTopics: ['Microservice Communication', 'JWT / OAuth2 Auth Flows', 'Dockerizing Apps', 'Cloud Deployment Pipelines'],
    projectOutcome: 'Deploy a multi-service authenticated web application to cloud infrastructure.',
    prerequisites: 'Full-stack web experience.',
    targetAudience: 'Advanced developers targeting enterprise software engineering.',
  },

  // ==================== DOMAIN 3: Data Analyst with AI & Automation ====================
  {
    id: 'da-1',
    domainId: 'data-analyst',
    domainTitle: 'Data Analyst with AI & Automation',
    numberInDomain: 1,
    title: 'Excel for Data Analysis',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master practical business spreadsheet functions, XLOOKUP, Pivot Tables, conditional formatting, and analytical charting in Excel.',
    keyTopics: ['Advanced Formulas & XLOOKUP', 'Pivot Tables & Pivot Charts', 'Data Validation & Cleaning', 'Business Dashboard Layouts'],
    projectOutcome: 'Build an executive sales performance dashboard with dynamic slicers.',
    prerequisites: 'Familiarity with spreadsheets.',
    targetAudience: 'Students and business analysts entering data analysis.',
  },
  {
    id: 'da-2',
    domainId: 'data-analyst',
    domainTitle: 'Data Analyst with AI & Automation',
    numberInDomain: 2,
    title: 'SQL for Analysts',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Query relational databases to extract business insights: multi-table JOINs, GROUP BY aggregations, subqueries, and window functions.',
    keyTopics: ['SELECT & Filtering Queries', 'INNER & LEFT JOINs', 'Aggregations & GROUP BY', 'Subqueries & CTEs'],
    projectOutcome: 'Analyze a retail e-commerce database to extract key KPI metrics and trends.',
    prerequisites: 'No prior SQL knowledge required.',
    targetAudience: 'Aspiring data analysts and business intelligence learners.',
  },
  {
    id: 'da-3',
    domainId: 'data-analyst',
    domainTitle: 'Data Analyst with AI & Automation',
    numberInDomain: 3,
    title: 'Dashboards with Power BI / Tableau',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Transform raw data into compelling interactive BI dashboards in Power BI and Tableau with DAX calculations and data models.',
    keyTopics: ['Data Modeling & Star Schema', 'DAX Measures & Calculated Columns', 'Interactive Visuals & Filters', 'Publishing Reports'],
    projectOutcome: 'Design and publish a multi-page operational business dashboard.',
    prerequisites: 'Basic Excel or SQL understanding.',
    targetAudience: 'Data professionals building executive visual reports.',
  },
  {
    id: 'da-4',
    domainId: 'data-analyst',
    domainTitle: 'Data Analyst with AI & Automation',
    numberInDomain: 4,
    title: 'Python for Data Cleaning and Automation',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Automate repetitive analytical workflows using Python, Pandas, and openpyxl: handling missing data, file batching, and automated exports.',
    keyTopics: ['Pandas Data Wrangling', 'Automating Excel with openpyxl', 'Handling Nulls & Outliers', 'Scheduled Script Runs'],
    projectOutcome: 'Create an automated script that ingests daily CSV files and generates clean summary reports.',
    prerequisites: 'Basic Python syntax.',
    targetAudience: 'Analysts looking to replace manual spreadsheet labor.',
  },
  {
    id: 'da-5',
    domainId: 'data-analyst',
    domainTitle: 'Data Analyst with AI & Automation',
    numberInDomain: 5,
    title: 'AI-Assisted Analytics for Faster Insights',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Leverage LLMs, natural language querying (Text-to-SQL), and automated EDA libraries to extract instant narrative insights from datasets.',
    keyTopics: ['LLM Text-to-SQL Pipelines', 'Automated EDA Tools', 'Natural Language Business Q&A', 'AI Chart Generation'],
    projectOutcome: 'Construct an AI copilot dashboard that answers data questions in plain English.',
    prerequisites: 'Solid SQL and Python foundations.',
    targetAudience: 'Advanced analysts modernizing analytical workflows.',
  },
  {
    id: 'da-6',
    domainId: 'data-analyst',
    domainTitle: 'Data Analyst with AI & Automation',
    numberInDomain: 6,
    title: 'Automated Reporting Pipelines',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Architect end-to-end automated pipelines that pull SQL database data, compute metrics, format reports, and auto-dispatch email digests.',
    keyTopics: ['End-to-End Pipeline Design', 'Automated Email Notification Scripts', 'Database Extract Schedulers', 'Error Logging & Alerts'],
    projectOutcome: 'Deploy a completely hands-off weekly executive KPI reporting pipeline.',
    prerequisites: 'Python, SQL, and database experience.',
    targetAudience: 'Senior analysts and BI engineers.',
  },

  // ==================== DOMAIN 4: Data Science & Machine Learning ====================
  {
    id: 'ds-1',
    domainId: 'data-science',
    domainTitle: 'Data Science & Machine Learning',
    numberInDomain: 1,
    title: 'Data Handling with NumPy and Pandas',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master fast array processing with NumPy and high-performance DataFrame operations, grouping, and merging with Pandas.',
    keyTopics: ['NumPy Vectorization', 'Pandas Indexing & Slicing', 'GroupBy & Aggregations', 'Data Cleaning Techniques'],
    projectOutcome: 'Process and analyze a multi-gigabyte transactional dataset in Python.',
    prerequisites: 'Basic Python knowledge.',
    targetAudience: 'Students beginning their data science journey.',
  },
  {
    id: 'ds-2',
    domainId: 'data-science',
    domainTitle: 'Data Science & Machine Learning',
    numberInDomain: 2,
    title: 'Data Visualization with Matplotlib and Seaborn',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Communicate data patterns effectively through exploratory data plots, correlation heatmaps, pairplots, and distribution curves.',
    keyTopics: ['Matplotlib Subplots & Customization', 'Seaborn Statistical Plots', 'Correlation Heatmaps', 'Visual Storytelling'],
    projectOutcome: 'Deliver a comprehensive exploratory data analysis (EDA) notebook with visual insights.',
    prerequisites: 'Basic Python and Pandas.',
    targetAudience: 'Aspiring data scientists and analysts.',
  },
  {
    id: 'ds-3',
    domainId: 'data-science',
    domainTitle: 'Data Science & Machine Learning',
    numberInDomain: 3,
    title: 'Feature Engineering and Model Building',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Learn one-hot encoding, scaling, imputation, feature selection, and model cross-validation to maximize predictive performance.',
    keyTopics: ['Categorical Encoding & Scaling', 'Feature Selection Methods', 'Cross-Validation Strategies', 'Hyperparameter Tuning with GridSearch'],
    projectOutcome: 'Engineer high-impact features and train optimized machine learning models.',
    prerequisites: 'Pandas and basic ML familiarity.',
    targetAudience: 'Intermediate data science practitioners.',
  },
  {
    id: 'ds-4',
    domainId: 'data-science',
    domainTitle: 'Data Science & Machine Learning',
    numberInDomain: 4,
    title: 'Regression, Classification and Clustering Hands-On',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Implement core ML algorithms: Random Forests, Gradient Boosting (XGBoost), Logistic Regression, and K-Means clustering.',
    keyTopics: ['Random Forest & Ensemble Methods', 'XGBoost & LightGBM', 'K-Means Clustering', 'ROC-AUC & Confusion Matrix'],
    projectOutcome: 'Build an end-to-end customer segmentation and credit risk prediction pipeline.',
    prerequisites: 'scikit-learn and feature engineering skills.',
    targetAudience: 'Developers mastering statistical ML models.',
  },
  {
    id: 'ds-5',
    domainId: 'data-science',
    domainTitle: 'Data Science & Machine Learning',
    numberInDomain: 5,
    title: 'Time-Series Forecasting',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Analyze temporal trends, seasonality, stationarity, and forecast future demand using ARIMA, SARIMA, and Prophet models.',
    keyTopics: ['Time Series Decomposition', 'Stationarity & Dickey-Fuller Test', 'ARIMA / SARIMA Modeling', 'Prophet Forecasting'],
    projectOutcome: 'Build an accurate product demand or energy consumption forecast model.',
    prerequisites: 'Intermediate machine learning and statistics.',
    targetAudience: 'Data scientists handling time-stamped business data.',
  },
  {
    id: 'ds-6',
    domainId: 'data-science',
    domainTitle: 'Data Science & Machine Learning',
    numberInDomain: 6,
    title: 'Model Deployment and MLOps Basics',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Containerize trained ML models with Docker, serve inference through FastAPI, and monitor data drift and model metrics.',
    keyTopics: ['Model Serialization (Pickle/ONNX)', 'FastAPI Inference Endpoints', 'Dockerizing Models', 'MLflow & Drift Monitoring'],
    projectOutcome: 'Deploy a live machine learning prediction REST API accessible by web clients.',
    prerequisites: 'Machine learning model building experience.',
    targetAudience: 'Data scientists transitioning models into production.',
  },

  // ==================== DOMAIN 5: Cybersecurity & Ethical Hacking ====================
  {
    id: 'cs-1',
    domainId: 'cyber-security',
    domainTitle: 'Cybersecurity & Ethical Hacking',
    numberInDomain: 1,
    title: 'Networking and Security Fundamentals',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Understand TCP/IP, OSI layers, DNS, subnetting, port protocols, firewall rules, and core cybersecurity principles.',
    keyTopics: ['OSI & TCP/IP Model', 'IP Subnetting & Ports', 'DNS, DHCP & HTTP/HTTPS', 'Basic Firewalls & NAT'],
    projectOutcome: 'Map a simulated enterprise local network and identify network vulnerabilities.',
    prerequisites: 'Basic computer and internet knowledge.',
    targetAudience: 'Students beginning cybersecurity education.',
  },
  {
    id: 'cs-2',
    domainId: 'cyber-security',
    domainTitle: 'Cybersecurity & Ethical Hacking',
    numberInDomain: 2,
    title: 'Kali Linux and Lab Setup',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Set up an isolated virtualization security lab with VirtualBox, Kali Linux, vulnerable target machines (Metasploitable), and Bash tools.',
    keyTopics: ['Virtualization & Lab Isolation', 'Kali Linux Navigation', 'Essential Bash Commands', 'Package Management & Security Tools'],
    projectOutcome: 'Configure a fully functional ethical hacking lab ready for safe security testing.',
    prerequisites: 'Basic computer literacy.',
    targetAudience: 'Learners preparing for ethical hacking training.',
  },
  {
    id: 'cs-3',
    domainId: 'cyber-security',
    domainTitle: 'Cybersecurity & Ethical Hacking',
    numberInDomain: 3,
    title: 'Web App Security and the OWASP Top 10',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Discover and remediate real web vulnerabilities: SQL Injection, Cross-Site Scripting (XSS), CSRF, and broken access controls using Burp Suite.',
    keyTopics: ['OWASP Top 10 Vulnerabilities', 'Burp Suite Proxy Configuration', 'SQL Injection (SQLi) Exploits', 'XSS & Session Hijacking'],
    projectOutcome: 'Perform a web application vulnerability scan and draft remediation recommendations.',
    prerequisites: 'Basic web technology (HTML/HTTP) knowledge.',
    targetAudience: 'Web developers and aspiring application security analysts.',
  },
  {
    id: 'cs-4',
    domainId: 'cyber-security',
    domainTitle: 'Cybersecurity & Ethical Hacking',
    numberInDomain: 4,
    title: 'Network Scanning with Nmap and Wireshark',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Perform active network reconnaissance using Nmap port scans and inspect packet traffic with Wireshark to identify unencrypted credentials.',
    keyTopics: ['Nmap Scan Types & NSE Scripts', 'Wireshark Packet Analysis', 'Detecting Insecure Protocols (HTTP, FTP)', 'Network Baseline Auditing'],
    projectOutcome: 'Execute a network security audit and identify open vulnerable services across a subnet.',
    prerequisites: 'Networking fundamentals and Linux basics.',
    targetAudience: 'Security enthusiasts and network engineers.',
  },
  {
    id: 'cs-5',
    domainId: 'cyber-security',
    domainTitle: 'Cybersecurity & Ethical Hacking',
    numberInDomain: 5,
    title: 'Penetration Testing Methodology',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Follow industry penetration testing frameworks: reconnaissance, weaponization, Metasploit exploitation, privilege escalation, and reporting.',
    keyTopics: ['Penetration Testing Stages', 'Metasploit Framework', 'Privilege Escalation Techniques', 'Professional Pen Test Reporting'],
    projectOutcome: 'Execute a full penetration test on a vulnerable test target and write an executive report.',
    prerequisites: 'Intermediate Linux, networking, and scanning skills.',
    targetAudience: 'Students and engineers targeting offensive security roles.',
  },
  {
    id: 'cs-6',
    domainId: 'cyber-security',
    domainTitle: 'Cybersecurity & Ethical Hacking',
    numberInDomain: 6,
    title: 'Incident Response and Digital Forensics',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Investigate security compromises: capture volatile memory, examine system event logs, reconstruct attack timelines, and preserve chain of custody.',
    keyTopics: ['Incident Response Life Cycle', 'Memory Forensics (Volatility)', 'Linux & Windows Log Forensics', 'Chain of Custody Documentation'],
    projectOutcome: 'Analyze a simulated security breach image and reconstruct the adversary attack path.',
    prerequisites: 'Operating system and security fundamentals.',
    targetAudience: 'SOC analysts and defensive security specialists.',
  },

  // ==================== DOMAIN 6: DevOps with AWS (AI & Automation Deployment) ====================
  {
    id: 'do-1',
    domainId: 'cloud-devops',
    domainTitle: 'DevOps with AWS (AI & Automation Deployment)',
    numberInDomain: 1,
    title: 'Linux, Git and GitHub Essentials',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master the command line, Linux permissions, package managers, and collaborative Git version control: branching, merging, and pull requests.',
    keyTopics: ['Linux File Hierarchy & Permissions', 'SSH Keys & Remote Servers', 'Git Branching & Rebasing', 'GitHub Team Collaboration'],
    projectOutcome: 'Set up an automated GitHub repository with branch protection and collaborative workflows.',
    prerequisites: 'Basic computer literacy.',
    targetAudience: 'Students and developers starting cloud and DevOps paths.',
  },
  {
    id: 'do-2',
    domainId: 'cloud-devops',
    domainTitle: 'DevOps with AWS (AI & Automation Deployment)',
    numberInDomain: 2,
    title: 'AWS Fundamentals (EC2, S3, IAM)',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Navigate AWS console and CLI: launch Linux EC2 virtual servers, configure S3 cloud storage buckets, and secure access with IAM roles.',
    keyTopics: ['AWS Global Infrastructure', 'EC2 Security Groups & Keypairs', 'S3 Static Hosting & Permissions', 'IAM Users, Groups & Policies'],
    projectOutcome: 'Launch a secure cloud web server on AWS EC2 backed by an S3 asset bucket.',
    prerequisites: 'Linux and networking fundamentals.',
    targetAudience: 'Engineers getting started with Amazon Web Services.',
  },
  {
    id: 'do-3',
    domainId: 'cloud-devops',
    domainTitle: 'DevOps with AWS (AI & Automation Deployment)',
    numberInDomain: 3,
    title: 'Docker and Containerization',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Containerize multi-tier web applications: write efficient Dockerfiles, manage images, handle volume persistence, and compose multi-container apps.',
    keyTopics: ['Docker Architecture & Daemon', 'Writing Clean Dockerfiles', 'Docker Compose Multi-Container', 'Container Networking & Storage'],
    projectOutcome: 'Containerize a web app with an attached database using Docker Compose.',
    prerequisites: 'Linux command line and basic programming.',
    targetAudience: 'Developers adopting modern containerized workflows.',
  },
  {
    id: 'do-4',
    domainId: 'cloud-devops',
    domainTitle: 'DevOps with AWS (AI & Automation Deployment)',
    numberInDomain: 4,
    title: 'CI/CD Pipelines with Jenkins / GitHub Actions',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Automate build, test, and release cycles: configure GitHub Actions YAML workflows and Jenkins automation pipelines with automated testing gates.',
    keyTopics: ['Continuous Integration Concepts', 'GitHub Actions Workflow Syntax', 'Automated Testing Gates', 'Artifact Storage & Deployment'],
    projectOutcome: 'Implement an automated CI/CD pipeline that tests code and builds Docker images on commit.',
    prerequisites: 'Git and Docker basics.',
    targetAudience: 'DevOps learners building automated delivery systems.',
  },
  {
    id: 'do-5',
    domainId: 'cloud-devops',
    domainTitle: 'DevOps with AWS (AI & Automation Deployment)',
    numberInDomain: 5,
    title: 'Kubernetes and Terraform (Infrastructure as Code)',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Provision AWS infrastructure reliably using Terraform declarative code, and orchestrate containerized microservices across Kubernetes clusters.',
    keyTopics: ['Terraform HCL Syntax & State', 'Provisioning AWS VPC & EC2', 'Kubernetes Pods, Deployments & Services', 'K8s Ingress & ConfigMaps'],
    projectOutcome: 'Provision cloud infrastructure with Terraform and deploy a load-balanced Kubernetes application.',
    prerequisites: 'Docker, AWS, and Linux skills.',
    targetAudience: 'Engineers designing enterprise cloud environments.',
  },
  {
    id: 'do-6',
    domainId: 'cloud-devops',
    domainTitle: 'DevOps with AWS (AI & Automation Deployment)',
    numberInDomain: 6,
    title: 'Deploying AI/ML Models on AWS with Monitoring',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Deploy machine learning and AI inference endpoints on AWS (ECS / SageMaker / Lambda), and monitor CPU, latency, and costs with CloudWatch.',
    keyTopics: ['Serving AI Models on AWS', 'Dockerizing ML Pipelines', 'AWS CloudWatch Metrics & Alarms', 'Autoscaling & Cost Optimization'],
    projectOutcome: 'Deploy a high-availability AI inference microservice on AWS with CloudWatch monitoring.',
    prerequisites: 'AWS, Docker, and machine learning deployment knowledge.',
    targetAudience: 'DevOps and MLOps engineers productionizing AI.',
  },

  // ==================== DOMAIN 7: Full Stack + Mobile Development ====================
  {
    id: 'mob-1',
    domainId: 'mobile-dev',
    domainTitle: 'Full Stack + Mobile Development',
    numberInDomain: 1,
    title: 'Mobile App Basics with Flutter / React Native',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Set up cross-platform mobile development environments, learn Dart/JSX syntax, and build fundamental mobile UI component hierarchies.',
    keyTopics: ['Flutter Widget Tree / React Native Views', 'Mobile Styling & Responsive Layouts', 'Debugging on Emulators', 'Asset Handling & Fonts'],
    projectOutcome: 'Build a mobile multi-screen profile and catalogue app running on Android and iOS simulators.',
    prerequisites: 'Basic programming knowledge in any language.',
    targetAudience: 'Students and web developers stepping into mobile development.',
  },
  {
    id: 'mob-2',
    domainId: 'mobile-dev',
    domainTitle: 'Full Stack + Mobile Development',
    numberInDomain: 2,
    title: 'UI Building and Navigation',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master stack, tab, and drawer navigation paradigms, handle touch gestures, and create clean, animated native mobile layouts.',
    keyTopics: ['Stack & Bottom Tab Navigation', 'Touch Gestures & Feedback', 'Form Inputs & Form Validation', 'Animated Transitions'],
    projectOutcome: 'Create a smooth multi-tab mobile application with clean nested navigation.',
    prerequisites: 'Basic Flutter or React Native foundations.',
    targetAudience: 'Mobile application developers.',
  },
  {
    id: 'mob-3',
    domainId: 'mobile-dev',
    domainTitle: 'Full Stack + Mobile Development',
    numberInDomain: 3,
    title: 'Connecting Apps to APIs and Firebase',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Connect mobile frontends to REST backend APIs and cloud services like Firebase Firestore for real-time data sync and cloud storage.',
    keyTopics: ['HTTP Networking & JSON Parsing', 'Firebase Firestore Realtime DB', 'Cloud Storage for Media', 'Offline Data Caching'],
    projectOutcome: 'Build a live cloud-connected mobile notes or task synchronization app.',
    prerequisites: 'Mobile UI and navigation foundations.',
    targetAudience: 'Developers building connected mobile products.',
  },
  {
    id: 'mob-4',
    domainId: 'mobile-dev',
    domainTitle: 'Full Stack + Mobile Development',
    numberInDomain: 4,
    title: 'State Management and Authentication',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Manage complex global state with Provider / Riverpod / Redux, and implement secure user registration, email login, and JWT token storage.',
    keyTopics: ['State Management Patterns', 'Firebase Auth / JWT Sessions', 'Secure Local Storage', 'Role-Based Screen Access'],
    projectOutcome: 'Implement a complete authentication workflow with persistent login state.',
    prerequisites: 'Mobile networking and API experience.',
    targetAudience: 'Intermediate mobile app developers.',
  },
  {
    id: 'mob-5',
    domainId: 'mobile-dev',
    domainTitle: 'Full Stack + Mobile Development',
    numberInDomain: 5,
    title: 'Publishing to Play Store and App Store',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Prepare production release builds: app signing, bundle optimization, permission handling, Play Console and App Store submission processes.',
    keyTopics: ['Android Keystores & iOS Certificates', 'App Bundle & IPA Generation', 'App Store / Play Store Guidelines', 'Crashlytics Integration'],
    projectOutcome: 'Configure, sign, and build a production-ready release APK/Bundle.',
    prerequisites: 'Completed mobile application experience.',
    targetAudience: 'Developers preparing to release applications to public stores.',
  },
  {
    id: 'mob-6',
    domainId: 'mobile-dev',
    domainTitle: 'Full Stack + Mobile Development',
    numberInDomain: 6,
    title: 'Integrating AI Features into Mobile Apps',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Integrate on-device or cloud AI capabilities into mobile apps: voice transcription, on-device vision classification, and conversational LLM bots.',
    keyTopics: ['Mobile AI SDKs (OpenAI / Gemini)', 'On-Device ML (TensorFlow Lite)', 'Camera & Image AI Analysis', 'Voice & Audio AI Interfaces'],
    projectOutcome: 'Build an AI-powered camera scanner or voice assistant mobile application.',
    prerequisites: 'Intermediate mobile development and API skills.',
    targetAudience: 'Mobile engineers incorporating next-generation AI features.',
  },

  // ==================== DOMAIN 8: Software Testing with Automation (Selenium) ====================
  {
    id: 'st-1',
    domainId: 'software-testing',
    domainTitle: 'Software Testing with Automation (Selenium)',
    numberInDomain: 1,
    title: 'Manual Testing, Test Cases and Bug Reporting',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Learn foundational QA methodologies: writing clear test cases, positive/negative test scenarios, defect severity, and logging in Jira.',
    keyTopics: ['Test Case Writing Formats', 'Boundary Value & Equivalence Partitioning', 'Bug Lifecycle & Severity/Priority', 'Defect Tracking in Jira'],
    projectOutcome: 'Write a comprehensive test specification and bug defect report for an e-commerce platform.',
    prerequisites: 'Basic computer literacy.',
    targetAudience: 'Students and beginners pursuing quality assurance careers.',
  },
  {
    id: 'st-2',
    domainId: 'software-testing',
    domainTitle: 'Software Testing with Automation (Selenium)',
    numberInDomain: 2,
    title: 'SDLC, STLC and Agile Testing',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Understand the role of QA across modern development lifecycles: Agile sprint ceremonies, sprint planning, user acceptance testing (UAT).',
    keyTopics: ['SDLC vs STLC Phases', 'Agile Scrum QA Ceremonies', 'Sprint Test Planning', 'Traceability Matrix (RTM)'],
    projectOutcome: 'Create a requirements traceability matrix and sprint testing plan.',
    prerequisites: 'Manual testing foundations.',
    targetAudience: 'QA specialists preparing for enterprise agile teams.',
  },
  {
    id: 'st-3',
    domainId: 'software-testing',
    domainTitle: 'Software Testing with Automation (Selenium)',
    numberInDomain: 3,
    title: 'Selenium WebDriver with Java / Python',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Automate web browser interactions with Selenium WebDriver: locating elements with XPath/CSS, handling dropdowns, alerts, and dynamic waits.',
    keyTopics: ['WebDriver Setup & Architecture', 'XPath & CSS Selectors', 'Implicit & Explicit Waits', 'Handling Alerts, Frames & Windows'],
    projectOutcome: 'Build an automated end-to-end user login and shopping checkout test script.',
    prerequisites: 'Basic Java or Python programming.',
    targetAudience: 'Manual testers transitioning into test automation.',
  },
  {
    id: 'st-4',
    domainId: 'software-testing',
    domainTitle: 'Software Testing with Automation (Selenium)',
    numberInDomain: 4,
    title: 'TestNG / PyTest Frameworks',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Structure automated test suites using TestNG (Java) or PyTest (Python) with data-driven testing, assertions, Page Object Model (POM), and reports.',
    keyTopics: ['Page Object Model Design', 'Assertions & Annotations', 'Data-Driven Testing (Excel/JSON)', 'HTML Test Execution Reports'],
    projectOutcome: 'Architect a robust Page Object Model automation test framework with HTML reporting.',
    prerequisites: 'Selenium WebDriver basics.',
    targetAudience: 'Automation QA engineers structuring scalable test repositories.',
  },
  {
    id: 'st-5',
    domainId: 'software-testing',
    domainTitle: 'Software Testing with Automation (Selenium)',
    numberInDomain: 5,
    title: 'API Testing with Postman and REST Assured',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Validate backend REST web services: automated status code checks, schema validations, authentication headers, and programmatic test scripts.',
    keyTopics: ['Postman Collections & Variables', 'Automated JS Tests in Postman', 'REST Assured Framework (Java)', 'JSON Schema Validation'],
    projectOutcome: 'Build an automated API regression test suite verifying backend web services.',
    prerequisites: 'Basic programming and API concepts.',
    targetAudience: 'QA engineers mastering backend service verification.',
  },
  {
    id: 'st-6',
    domainId: 'software-testing',
    domainTitle: 'Software Testing with Automation (Selenium)',
    numberInDomain: 6,
    title: 'CI/CD Test Automation and AI-Powered Testing Tools',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Integrate automation suites into CI/CD pipelines (Jenkins/GitHub Actions) and leverage modern AI tools for automated test generation.',
    keyTopics: ['Running Tests in Headless Mode', 'GitHub Actions Test Integration', 'AI Test Generation Tools', 'Automated Regression Gates'],
    projectOutcome: 'Deploy an automated continuous testing pipeline triggered on every code commit.',
    prerequisites: 'Test automation frameworks and Git basics.',
    targetAudience: 'Lead QA automation engineers.',
  },

  // ==================== DOMAIN 9: Business Analyst ====================
  {
    id: 'ba-1',
    domainId: 'business-analyst',
    domainTitle: 'Business Analyst',
    numberInDomain: 1,
    title: 'BA Role, SDLC and Requirement Gathering',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Learn the core responsibilities of a Business Analyst, requirement elicitation techniques (interviews, surveys), and stakeholder management.',
    keyTopics: ['BA Core Competencies', 'Requirement Elicitation Methods', 'Stakeholder Identification & Mapping', 'Business Problem Definition'],
    projectOutcome: 'Conduct a simulated business interview and draft initial scope requirements.',
    prerequisites: 'No technical prerequisites required.',
    targetAudience: 'Students and professionals transitioning into business analysis.',
  },
  {
    id: 'ba-2',
    domainId: 'business-analyst',
    domainTitle: 'Business Analyst',
    numberInDomain: 2,
    title: 'Documentation: BRD, FRD and User Stories',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Author formal specification documents: Business Requirement Documents (BRD), Functional Requirement Documents (FRD), and Agile user stories.',
    keyTopics: ['BRD Document Structure', 'FRD Technical Specifications', 'Agile User Story Writing', 'Acceptance Criteria (Gherkin/INVEST)'],
    projectOutcome: 'Create a comprehensive BRD and user story backlog for a new software feature.',
    prerequisites: 'Basic requirement gathering understanding.',
    targetAudience: 'Aspiring business analysts and product managers.',
  },
  {
    id: 'ba-3',
    domainId: 'business-analyst',
    domainTitle: 'Business Analyst',
    numberInDomain: 3,
    title: 'Process Modeling with UML and BPMN',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Visually communicate business logic and system interactions using Use Case diagrams, Activity diagrams, and BPMN 2.0 process flowcharts.',
    keyTopics: ['BPMN 2.0 Process Flowcharts', 'UML Use Case Diagrams', 'Activity & Sequence Diagrams', 'Current vs Future State Mapping'],
    projectOutcome: 'Model an end-to-end banking loan approval or order fulfillment process.',
    prerequisites: 'Requirement analysis foundations.',
    targetAudience: 'Business analysts designing system workflows.',
  },
  {
    id: 'ba-4',
    domainId: 'business-analyst',
    domainTitle: 'Business Analyst',
    numberInDomain: 4,
    title: 'Wireframing and Jira / Confluence',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Translate user requirements into low-fidelity UI wireframes and manage requirements, sprint backlogs, and team documentation in Jira and Confluence.',
    keyTopics: ['Low-Fidelity Wireframing Tools', 'Jira Sprint & Epic Management', 'Confluence Product Documentation', 'Dev Team Design Handoffs'],
    projectOutcome: 'Build an interactive wireframe and configure a Jira backlog with user stories.',
    prerequisites: 'User story writing experience.',
    targetAudience: 'Business analysts collaborating with UX and engineering teams.',
  },
  {
    id: 'ba-5',
    domainId: 'business-analyst',
    domainTitle: 'Business Analyst',
    numberInDomain: 5,
    title: 'Data-Driven Decision Making with SQL and Power BI',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Validate business assumptions and measure feature ROI by querying relational SQL databases and building analytical Power BI KPI reports.',
    keyTopics: ['Business-Focused SQL Queries', 'Cost-Benefit Analysis', 'Power BI KPI Dashboards', 'Presenting Data to Executives'],
    projectOutcome: 'Deliver a data-backed business recommendation report with supporting SQL analytics.',
    prerequisites: 'Basic SQL and business documentation knowledge.',
    targetAudience: 'Senior business analysts and strategy associates.',
  },
  {
    id: 'ba-6',
    domainId: 'business-analyst',
    domainTitle: 'Business Analyst',
    numberInDomain: 6,
    title: 'Stakeholder Management and Case-Study Capstone',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Tackle a real-world enterprise problem statement: negotiation, scope changes, UAT management, and final executive stakeholder presentation.',
    keyTopics: ['Managing Conflicting Stakeholders', 'Change Request Management', 'UAT Sign-Off Procedures', 'Executive Capstone Presentation'],
    projectOutcome: 'Present a complete end-to-end digital transformation capstone proposal.',
    prerequisites: 'Comprehensive business analysis coursework.',
    targetAudience: 'Professionals preparing for senior business analyst roles.',
  },

  // ==================== DOMAIN 10: ServiceNow, Salesforce & CRM ====================
  {
    id: 'crm-1',
    domainId: 'crm-cloud',
    domainTitle: 'ServiceNow, Salesforce & CRM',
    numberInDomain: 1,
    title: 'CRM Fundamentals and Platform Tour',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Understand customer relationship management principles, lead-to-opportunity lifecycles, and explore core Salesforce and ServiceNow cloud architectures.',
    keyTopics: ['CRM Industry Landscape', 'Lead, Contact & Opportunity Lifecycle', 'Cloud Platform Architecture', 'User Interface Navigation'],
    projectOutcome: 'Configure a customized sales tracking pipeline in a CRM sandbox environment.',
    prerequisites: 'No technical prerequisites required.',
    targetAudience: 'Students and IT learners exploring enterprise CRM platforms.',
  },
  {
    id: 'crm-2',
    domainId: 'crm-cloud',
    domainTitle: 'ServiceNow, Salesforce & CRM',
    numberInDomain: 2,
    title: 'Salesforce Admin Basics (Objects, Fields, Users)',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master Salesforce administration: creating Custom Objects, custom fields, data validation rules, page layouts, and user security permissions.',
    keyTopics: ['Standard vs Custom Objects', 'Field Types & Validation Rules', 'Profiles, Roles & Permission Sets', 'Page Layout Customization'],
    projectOutcome: 'Build an operational custom event registration system inside Salesforce.',
    prerequisites: 'CRM fundamentals knowledge.',
    targetAudience: 'Aspiring Salesforce administrators.',
  },
  {
    id: 'crm-3',
    domainId: 'crm-cloud',
    domainTitle: 'ServiceNow, Salesforce & CRM',
    numberInDomain: 3,
    title: 'Flows and Process Automation',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Automate business logic with no-code tools: building record-triggered Flows, screen Flows, scheduled paths, and email alerts in Salesforce.',
    keyTopics: ['Record-Triggered Flows', 'Screen Flows for User Guides', 'Formula Fields & Email Alerts', 'Debugging Flow Errors'],
    projectOutcome: 'Automate a multi-step customer escalation and approval workflow.',
    prerequisites: 'Salesforce Admin basics.',
    targetAudience: 'Salesforce admins and business automation developers.',
  },
  {
    id: 'crm-4',
    domainId: 'crm-cloud',
    domainTitle: 'ServiceNow, Salesforce & CRM',
    numberInDomain: 4,
    title: 'ServiceNow ITSM (Incidents, Requests, Catalog)',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Explore IT Service Management (ITSM) in ServiceNow: managing Incident tickets, Problem management, Change requests, and building Service Catalog items.',
    keyTopics: ['Incident & Problem Management', 'Change Management Workflows', 'Service Catalog Item Design', 'SLA Configuration & Routing'],
    projectOutcome: 'Create a published IT Service Catalog item with automated assignment routing.',
    prerequisites: 'IT support or CRM familiarity.',
    targetAudience: 'ITSM specialists and ServiceNow developers.',
  },
  {
    id: 'crm-5',
    domainId: 'crm-cloud',
    domainTitle: 'ServiceNow, Salesforce & CRM',
    numberInDomain: 5,
    title: 'Apex and Lightning Development',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Programmatic development on Salesforce: writing Apex classes and triggers, SOQL database queries, test classes, and custom Lightning Web Components (LWC).',
    keyTopics: ['Apex Triggers & Bulkification', 'SOQL & SOSL Querying', 'Unit Testing & Code Coverage', 'Lightning Web Components (LWC)'],
    projectOutcome: 'Develop an automated Apex trigger and custom LWC user dashboard component.',
    prerequisites: 'Java/JavaScript and Salesforce Admin experience.',
    targetAudience: 'Developers targeting Salesforce engineering roles.',
  },
  {
    id: 'crm-6',
    domainId: 'crm-cloud',
    domainTitle: 'ServiceNow, Salesforce & CRM',
    numberInDomain: 6,
    title: 'Integrations, Reports and Dashboards',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Connect enterprise CRM platforms via REST/SOAP APIs, import bulk data, and build executive analytical reports and KPI dashboards.',
    keyTopics: ['REST API Integrations', 'Data Import Wizard & Data Loader', 'Matrix & Summary Reports', 'Executive Real-Time Dashboards'],
    projectOutcome: 'Build an external REST API integration feeding real-time data into executive dashboards.',
    prerequisites: 'Apex/ITSM development foundations.',
    targetAudience: 'Senior CRM consultants and solution architects.',
  },

  // ==================== DOMAIN 11: UI/UX Design ====================
  {
    id: 'ux-1',
    domainId: 'ui-ux',
    domainTitle: 'UI/UX Design',
    numberInDomain: 1,
    title: 'Design Principles, Color and Typography',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Learn visual design fundamentals: color psychology, accessible contrast ratios, font pairings, visual hierarchy, and spatial grids.',
    keyTopics: ['Visual Hierarchy & Alignment', 'Color Theory & Contrast (WCAG)', 'Typography Systems & Pairing', '8pt Grid Systems'],
    projectOutcome: 'Create a foundational digital brand style guide with colors and typography.',
    prerequisites: 'No prior design experience required.',
    targetAudience: 'Students and beginners pursuing product design careers.',
  },
  {
    id: 'ux-2',
    domainId: 'ui-ux',
    domainTitle: 'UI/UX Design',
    numberInDomain: 2,
    title: 'Figma Fundamentals',
    level: 'Basic',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master Figma tools: vector networks, frames, groups, responsive Auto Layout, component variants, and smart prototyping interactions.',
    keyTopics: ['Figma Interface & Frames', 'Auto Layout Rules', 'Components & Component Variants', 'Interactive Clickable Prototypes'],
    projectOutcome: 'Design an interactive multi-screen mobile app prototype in Figma.',
    prerequisites: 'Basic design principles knowledge.',
    targetAudience: 'Aspiring UI/UX designers and front-end developers.',
  },
  {
    id: 'ux-3',
    domainId: 'ui-ux',
    domainTitle: 'UI/UX Design',
    numberInDomain: 3,
    title: 'User Research, Wireframing and Prototyping',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Conduct user interviews, synthesize empathy maps and personas, map user journeys, and sketch rapid low-to-medium fidelity wireframes.',
    keyTopics: ['User Research & Personas', 'User Journey Mapping', 'Information Architecture & Sitemaps', 'Interactive Wireframing'],
    projectOutcome: 'Produce a complete UX discovery package and wireframe prototype.',
    prerequisites: 'Figma tool foundations.',
    targetAudience: 'UX researchers and product designers.',
  },
  {
    id: 'ux-4',
    domainId: 'ui-ux',
    domainTitle: 'UI/UX Design',
    numberInDomain: 4,
    title: 'Designing Mobile and Web Apps End to End',
    level: 'Intermediate',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Design comprehensive high-fidelity interfaces for responsive web and mobile: e-commerce flows, dashboards, micro-interactions, and animations.',
    keyTopics: ['Mobile iOS / Android UI Patterns', 'Responsive Desktop Dashboard Design', 'Micro-Interactions with Smart Animate', 'Asset Export & Developer Handoff'],
    projectOutcome: 'Design a complete high-fidelity SaaS dashboard and companion mobile app.',
    prerequisites: 'Figma Auto Layout and prototyping proficiency.',
    targetAudience: 'Product designers crafting polished interfaces.',
  },
  {
    id: 'ux-5',
    domainId: 'ui-ux',
    domainTitle: 'UI/UX Design',
    numberInDomain: 5,
    title: 'Design Systems and Accessibility',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Build scalable design systems in Figma: design tokens, atomic components, dark mode variants, and WCAG AA accessibility compliance.',
    keyTopics: ['Design Tokens & Variables', 'Atomic Design Methodology', 'WCAG AA Accessibility Standards', 'Maintaining Design Systems at Scale'],
    projectOutcome: 'Publish a scalable design system library with interactive components.',
    prerequisites: 'Intermediate Figma component mastery.',
    targetAudience: 'Senior UI designers and design system engineers.',
  },
  {
    id: 'ux-6',
    domainId: 'ui-ux',
    domainTitle: 'UI/UX Design',
    numberInDomain: 6,
    title: 'Portfolio Building and Usability Testing',
    level: 'Advanced',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Run moderated usability testing sessions, synthesize feedback, and assemble an industry-ready case study for placement interviews.',
    keyTopics: ['Usability Test Plans & Metrics', 'A/B Testing Methodologies', 'UX Case Study Storytelling', 'Portfolio Presentation Skills'],
    projectOutcome: 'Publish a portfolio-ready UX case study showcasing real research and design iterations.',
    prerequisites: 'Completed end-to-end design projects.',
    targetAudience: 'Designers preparing for corporate design job interviews.',
  },
];

export const FOUNDATION_WORKSHOPS: FoundationWorkshop[] = [
  {
    id: 'found-sql',
    number: 1,
    title: 'SQL from Scratch',
    tagline: 'Database Querying, Relational Joins & Real-World Business Schemas',
    duration: '1 Day (6-8 Hours)',
    description: 'Designed as an essential universal skill across all technology domains. Learn SQL querying from the ground up: database tables, SELECT filtering, aggregates, and multi-table relational joins.',
    keyTopics: [
      'Relational Database Architecture & Tables',
      'Filtering, Ordering & Pattern Matching (WHERE, LIKE)',
      'Aggregations & Grouping (COUNT, SUM, AVG, GROUP BY)',
      'Multi-Table Joins (INNER, LEFT, RIGHT, FULL)',
      'Subqueries & Essential Business Reporting Queries'
    ],
    handsOnOutcome: 'Query a real e-commerce transactional database and generate business analytics reports.',
  },
  {
    id: 'found-dsa',
    number: 2,
    title: 'DSA Basics in Python / Java',
    tagline: 'Core Data Structures, Algorithms & Algorithmic Complexity',
    duration: '1-2 Days (8-16 Hours)',
    description: 'Master practical algorithms and data structures: Big-O notation, arrays, linked lists, stacks, queues, hash maps, binary search, and recursive problem solving.',
    keyTopics: [
      'Time & Space Complexity (Big-O Notation)',
      'Arrays, Dynamic Lists & Matrix Manipulation',
      'Stacks, Queues & Hash Maps (Hash Tables)',
      'Sorting & Searching Algorithms (Binary Search, Merge Sort)',
      'Recursion & Tree Traversal Fundamentals'
    ],
    handsOnOutcome: 'Implement and benchmark core data structures solving competitive coding problems.',
  },
  {
    id: 'found-problem-solving',
    number: 3,
    title: 'Problem Solving for Interviews',
    tagline: 'Coding Patterns, Technical Assessment Strategy & Whiteboard Challenges',
    duration: '1 Day (6-8 Hours)',
    description: 'Prepare for software engineering placement drives and technical screening rounds. Master two-pointer techniques, sliding windows, recursion, and debugging under interview conditions.',
    keyTopics: [
      'Two-Pointer & Sliding Window Patterns',
      'Prefix Sums & Frequency Maps',
      'Handling Edge Cases & Boundary Conditions',
      'Whiteboard Code Explanation & Communication',
      'Live Coding Timed Mock Assessments'
    ],
    handsOnOutcome: 'Solve and explain 15+ curated standard technical interview problems with optimal complexity.',
  },
];

export const WORKSHOP_PROGRESSION_STAGES = [
  {
    stage: '01',
    name: 'DISCOVER',
    subtitle: 'Foundation & Principles',
    description: 'Hands-on exposure to core paradigms, tools, and technical architectures with live environment setup.',
    badge: 'Stage 1',
  },
  {
    stage: '02',
    name: 'LEARN',
    subtitle: 'Guided Implementation',
    description: 'Step-by-step code execution alongside experienced mentors solving practical challenges.',
    badge: 'Stage 2',
  },
  {
    stage: '03',
    name: 'BUILD',
    subtitle: 'Real-World Execution',
    description: 'Construct functional modules, integrate databases, deploy endpoints, and handle real datasets.',
    badge: 'Stage 3',
  },
  {
    stage: '04',
    name: 'APPLY',
    subtitle: 'Industrial Relevance',
    description: 'Harden code, address edge cases, implement authentication, and align with enterprise standards.',
    badge: 'Stage 4',
  },
  {
    stage: '05',
    name: 'CREATE',
    subtitle: 'Portfolio Artifacts',
    description: 'Complete deployable capstone projects with verifiable GitHub repositories and verified credentials.',
    badge: 'Career Launch',
  },
];

export const WORKSHOP_PROGRESSION = WORKSHOP_PROGRESSION_STAGES;

export const WORKSHOP_VIDEOS: WorkshopVideoItem[] = [
  {
    id: 'wk-vid-1',
    title: 'Independence Day Celebration',
    collegeOrEvent: 'Student & Community Outreach',
    aspectRatio: 'landscape',
    src: '/workshops/videos/workshop_video_1.mp4',
    poster: '/workshops/posters/poster_1.jpg',
    caption: 'A special Independence Day celebration with children, bringing the CSL community together through meaningful interactions and a stationery donation initiative.',
    tag: 'Community Outreach',
  },
  {
    id: 'wk-vid-2',
    title: 'Ethiraj College for Women Workshop Session',
    collegeOrEvent: 'Ethiraj College for Women, Chennai',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_2.mp4',
    poster: '/workshops/posters/poster_2.jpg',
    caption: 'Empowering students with industry-standard development workflows and practical guidance.',
    tag: 'Campus Workshop',
  },
  {
    id: 'wk-vid-3',
    title: 'Interactive Hands-On Seminar & Practical Coding',
    collegeOrEvent: 'Engineering College Campus',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_3.mp4',
    poster: '/workshops/posters/poster_3.jpg',
    caption: 'Real-time student engagement, live debugging, and collaborative breakout sessions.',
    tag: 'Live Seminar',
  },
  {
    id: 'wk-vid-4',
    title: 'Real Learning Happens When You Participate',
    collegeOrEvent: 'Hands-On Tech Lab',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_4.mp4',
    poster: '/workshops/posters/poster_4.jpg',
    caption: 'Students actively writing code, deploying modules, and presenting working solutions.',
    tag: 'Interactive Lab',
  },
  {
    id: 'wk-vid-5',
    title: 'Bridging the Gap: Campus to Corporate Readiness',
    collegeOrEvent: 'Industry Technology Workshop',
    aspectRatio: 'portrait',
    src: '/workshops/videos/workshop_video_5.mp4',
    poster: '/workshops/posters/poster_5.jpg',
    caption: 'Industry mentors demystifying real-world corporate expectations, tools, and career pathways.',
    tag: 'Career Readiness',
  },
];

export const WHY_CHOOSE_WORKSHOPS = [
  {
    num: '01',
    title: 'Hands-On Learning',
    description: 'Zero passive lecturing. Every workshop requires participants to write live code, configure environments, and build functioning modules in university computer labs.',
  },
  {
    num: '02',
    title: 'Industry-Relevant Tools',
    description: 'Learn production stacks, modern AI integrations, and enterprise frameworks co-designed with software engineers and industry practitioners.',
  },
  {
    num: '03',
    title: 'Guided Practical Projects',
    description: 'Participants build tangible capstone deliverables with clean GitHub repositories and verifiable completion credentials for job interviews.',
  },
];
